---
settings:
  name: Release notes
  rss_page: whats-new.html
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  release_notes_autogen:
    auto_release_notes_enabled: true
    repositories_features:
    - workload-fsx-ontap
    - workload-databases
    - workload-vmware
    - workload-genai
    - workload-setup-admin
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Notes de mise à jour d'usine de la charge de travail BlueXP 
    url: "/index.html"
  - title: Modifications récentes
    url: "/whats-new.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: BlueXP workload factory
  repo: workload-family
