= 4 août 2024
:allow-uri-read: 




== 4 août 2024

Directive non résolue dans <stdin> - include::_include/Workload-fsx-ONTAP.adoc[] :leveloffset: +1



=== Prise en charge de Terraform

Vous pouvez désormais utiliser Terraform à partir de Codebox pour déployer et gérer des systèmes de fichiers et des machines virtuelles de stockage.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Créez un système de fichiers"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-storage-vm.html["Créez une machine virtuelle de stockage"]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["Utiliser Terraform à partir de Codebox"^]




=== Recommandations de débit et d'IOPS dans le calculateur de stockage

Le calculateur de stockage fait des recommandations de configuration de système de fichiers FSX pour ONTAP pour le débit et les IOPS en fonction des bonnes pratiques AWS, qui vous guide de façon optimale pour votre sélection.



== 7 juillet 2024

Directive non résolue dans <stdin> - include::_include/Workload-fsx-ONTAP.adoc[] :leveloffset: +1



=== Version initiale de Workload Factory pour Amazon FSX for NetApp ONTAP

Amazon FSX pour NetApp ONTAP est désormais disponible dans Workload Factory.
