---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: 'Découvrez les derniers changements apportés aux charges de travail de l"usine BlueXP .' 
---
= Modifications récentes de l'usine de workloads BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Découvrez les derniers changements apportés aux charges de travail de l'usine BlueXP .



== 2025-06-29



=== Workloads VMware



==== Présentation de la prise en charge du conseiller de migration pour Amazon Elastic VMware Service

L'usine de charges de travail BlueXP pour VMware prend désormais en charge Amazon Elastic VMware Service. Grâce à l'assistant de migration, vous pouvez migrer rapidement vos charges de travail VMware sur site vers Amazon Elastic VMware Service. Vous optimisez ainsi vos coûts et bénéficiez d'un meilleur contrôle sur votre environnement VMware sans avoir à refactoriser ou à repenser la plateforme de vos applications.

https://docs.netapp.com/us-en/workload-vmware/launch-migration-advisor-evs-manual.html["Créer un plan de déploiement pour Amazon EVS à l'aide du conseiller de migration"]



=== Charges de travail GenAI



==== Prise en charge des sources de données hébergées sur des systèmes de fichiers NFS/SMB génériques

Vous pouvez désormais ajouter une source de données à partir d'un partage SMB ou NFS générique. Cela vous permet d'inclure des fichiers stockés sur des volumes hébergés par des systèmes de fichiers autres qu'Amazon FSx pour NetApp ONTAP.

https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["Ajouter des sources de données à une base de connaissances"]

https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html#add-data-sources-to-the-connector["Ajouter des sources de données à un connecteur"]



=== Configuration et administration



==== Prise en charge du service de notification de l'usine de charge de travail BlueXP

Le service de notification de l'usine de charge de travail BlueXP permet à l'usine de charge de travail d'envoyer des notifications au service d'alertes BlueXP ou à une rubrique Amazon SNS. Les notifications envoyées aux alertes BlueXP apparaissent dans le panneau des alertes BlueXP. Lorsque la fabrique de charges de travail publie des notifications dans une rubrique Amazon SNS, les abonnés à cette rubrique (tels que les personnes ou d'autres applications) reçoivent les notifications aux points de terminaison configurés pour cette rubrique (tels que les e-mails ou les SMS).

https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Configurer les notifications de l'usine de charge de travail BlueXP"]



== 2025-06-16



=== Charges de travail des constructeurs



==== Prise en charge du clonage

Vous pouvez désormais cloner un projet dans la Workload Factory de BlueXP pour Builders. Lorsque vous clonez un projet, Builders crée un nouveau projet à partir d'un snapshot, avec la même configuration que l'original. Le clonage est utile pour créer rapidement des projets similaires ou à des fins de test. Vous pouvez monter le nouveau clone de projet en suivant les instructions de Builders.

https://docs.netapp.com/us-en/workload-builders/version-projects.html["Gérer les versions de l'usine de charge de travail BlueXP pour les projets Builders"]



== 2025-06-08



=== Amazon FSX pour NetApp ONTAP



==== Nouvelle analyse et assistance bien conçues pour résoudre les problèmes

La gestion automatique de la capacité des systèmes de fichiers FSx for ONTAP est désormais incluse en tant qu'analyse de configuration dans le tableau de bord d'état bien architecturé.

De plus, Workload Factory prend désormais en charge la résolution des problèmes de configuration suivants :

* Seuil de capacité SSD
* Tiering des données
* Snapshots locaux planifiés
* FSx pour les sauvegardes ONTAP
* Réplication des données à distance
* Fonctionnalités d'efficacité du stockage
* Gestion automatique de la capacité


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Résoudre les problèmes de configuration"]



== 2025-06-03



=== Amazon FSX pour NetApp ONTAP



==== Amélioration de la croissance automatique du volume

Vous pouvez désormais définir la taille de croissance automatique de vos volumes afin que la taille du volume puisse croître au-delà de la taille provisionnée pour les besoins de l'entreprise et les exigences des applications.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/edit-volume-autogrow.html["Activer la croissance automatique de volumes"]



==== Mise à jour de l'analyse bien architecturée

Workload Factory analyse désormais vos systèmes de fichiers FSx for ONTAP afin de vérifier l'efficacité du stockage, notamment en termes de compactage, de compression et de déduplication des données. L'efficacité du stockage mesure l'efficacité avec laquelle les systèmes de fichiers utilisent l'espace disponible.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Visualisez l'état d'efficacité du stockage bien conçu"]



==== Améliorations du tableau de bord de stockage

À partir d'aujourd'hui, lorsque vous ouvrez la charge de travail Stockage depuis la console Workload Factory, vous accédez au *Tableau de bord*. Ce nouveau tableau de bord offre une vue d'ensemble de vos systèmes FSx for ONTAP, incluant le nombre de systèmes de fichiers, la capacité totale des SSD, l'état de l'architecture, la protection des données et l'intégrité de la relation de réplication.



==== Améliorations de l'onglet Volumes

La charge de travail Stockage a apporté des améliorations à l'onglet « Volumes » d'un système de fichiers FSx for ONTAP dans la console Workload Factory. Ces améliorations incluent :

* *Nouvelles cartes* : capacité SSD, pool de capacité et protection autonome contre les ransomwares (ARP)
* *Nouvelles colonnes* : Répartition de la capacité, Capacité SSD utilisée, Pool de capacité utilisée et Efficacité SSD




==== Mise à jour de l'efficacité du stockage pour la création de volumes

Lors de la création d'un nouveau volume, les fonctions d'efficacité du stockage, notamment le compactage, la compression et la déduplication des données, sont activées par défaut.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Créer un nouveau volume dans la fabrique de charges de travail"]



=== Charges de travail des bases de données



==== Détection PostgreSQL et Oracle

Vous pouvez désormais découvrir les instances exécutant des bases de données PostgreSQL et des déploiements de bases de données Oracle sur votre compte AWS depuis la console Workload Factory. Les instances découvertes apparaîtront dans l'inventaire des bases de données.



==== Terminologie « Optimisation » mise à jour

Auparavant appelée « Optimisation », Workload Factory utilise désormais « problèmes bien architecturés » et « état bien architecturé » pour décrire l'analyse des configurations de base de données et « correctif » pour décrire la correction des opportunités d'amélioration des configurations de base de données afin de répondre aux recommandations des meilleures pratiques.

link:https://docs.netapp.com/us-en/workload-databases/optimize-overview.html["Analyse de configuration pour les environnements de base de données dans Workload Factory"]



==== Intégration améliorée pour les instances hôtes

Au lieu des termes « non détecté », « non géré » ou « géré » pour la gestion des instances hôtes, Workload Factory utilise désormais « registre » pour l'intégration des instances hôtes. Le nouveau processus d'enregistrement inclut l'authentification et la préparation des instances hôtes afin que vous puissiez créer, surveiller, analyser et corriger les ressources dans vos configurations de base de données depuis la console Workload Factory. L'étape de préparation du processus d'enregistrement indique si vos instances hôtes sont prêtes à être gérées.

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["Gestion des instances"]



=== Charges de travail GenAI



==== Tracker disponible pour les opérations de surveillance et de suivi

La fonctionnalité de surveillance Tracker est désormais disponible dans GenAI. Vous pouvez utiliser Tracker pour surveiller et suivre la progression et l'état des opérations en attente, en cours et terminées, consulter les détails des tâches et sous-tâches opérationnelles, diagnostiquer les problèmes ou les échecs, modifier les paramètres des opérations ayant échoué et relancer les opérations ayant échoué.

link:https://docs.netapp.com/us-en/workload-genai/general/monitor-operations.html["Surveillez les opérations de charge de travail avec Tracker dans l'usine de charge de travail BlueXP"]



==== Choisir un modèle de reranker pour une base de connaissances

Vous pouvez désormais améliorer la pertinence des résultats de requêtes reclassés en sélectionnant un modèle de reranking spécifique à utiliser avec une base de connaissances. GenAI prend en charge les modèles Cohere Rerank et Amazon Rerank.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["Créer une base de connaissances GenAI"]



== 2025-05-04



=== Amazon FSX pour NetApp ONTAP



==== Protection anti-ransomware autonome pour les systèmes de fichiers FSX pour ONTAP

Protégez vos données avec la protection anti-ransomware autonome (ARP), une fonctionnalité qui utilise l'analyse des workloads dans les environnements NAS (NFS/SMB) pour détecter et signaler les activités anormales qui pourraient être une attaque par ransomware. Lorsqu'une attaque est suspectée, ARP crée également de nouveaux snapshots immuables à partir desquels vous pouvez restaurer vos données.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["Protégez vos données avec la protection anti-ransomware autonome"]



==== Amélioration du rééquilibrage des volumes FlexGroup

BlueXP  Workload Factory lance l'assistant de rééquilibrage des volumes FlexGroup avec plusieurs options de disposition pour le rééquilibrage des données dans un volume FlexGroup. Le rééquilibrage redistribue les données de façon homogène vers les volumes de membres FlexGroup.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/rebalance-volume.html["Rééquilibrez la capacité d'un volume FlexGroup"]



==== Implémentez les bonnes pratiques pour un système de fichiers FSX pour ONTAP

La fabrique de charges de travail BlueXP  fournit un tableau de bord dans lequel vous pouvez consulter l'état de l'architecture de vos configurations de système de fichiers. Cette analyse vous permet d'implémenter les bonnes pratiques pour vos systèmes de fichiers FSX pour ONTAP. L'analyse de la configuration du système de fichiers comprend les configurations suivantes : seuil de capacité SSD, snapshots locaux programmés, sauvegardes FSX pour ONTAP, Tiering des données et réplication des données à distance.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html["En savoir plus sur l'analyse bien conçue pour les configurations de système de fichiers"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Implémentez les meilleures pratiques pour vos systèmes de fichiers"]




==== Options de type de sécurité des volumes à double protocole

Vous avez la possibilité de choisir NTFS ou UNIX comme style de sécurité pour un volume afin de déterminer la méthode d'accès des utilisateurs et des autorisations à un volume.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Créer un volume"]



==== Amélioration de la réplication



===== Réplication inverse prise en charge à partir de FSX pour ONTAP vers l'environnement sur site

La réplication inverse est désormais disponible depuis un système de fichiers FSX pour ONTAP vers un cluster ONTAP sur site depuis la console d'usine des workloads.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/reverse-replication.html["Réplication inverse"]



===== Réplication de volume de protection des données

Il est désormais possible de répliquer des volumes de protection des données.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/cascade-replication.html["Réplication d'un volume de protection des données"]



===== Sélection de plusieurs volumes

La sélection de plusieurs volumes est disponible pour vous permettre de sélectionner exactement les volumes à répliquer.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Créer une relation de réplication"]



===== Étiquettes de politique de conservation à long terme

Lorsque vous activez la conservation à long terme pour une relation de réplication, les étiquettes des volumes source et cible doivent correspondre exactement. Désormais, l'usine de workloads BlueXP  peut automatiquement créer des étiquettes de volume source manquantes pour vous.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Créer une relation de réplication"]



==== Nom de fichier FSX pour ONTAP visible lors de la création du volume

Nous avons amélioré la visibilité des systèmes de fichiers FSX pour ONTAP lors de la création des volumes. Lorsque vous créez un volume, le système de fichiers FSX pour ONTAP s'affiche. Vous savez ainsi exactement où le volume est créé.



==== Compte AWS visible dans l'ensemble de la charge de travail stockage

Nous avons amélioré la visibilité des comptes sur la charge de travail de stockage. Le compte AWS s'affiche lorsque vous accédez aux onglets *volumes*, *Storage VM* et *Replication*.



==== Améliorations de l'association de liens

* Vous pouvez rapidement associer un lien à partir d'un système de fichiers FSX pour ONTAP dans l'onglet Inventaire.
* La fabrique de charges de travail BlueXP  prend désormais en charge l'utilisation d'autres informations d'identification utilisateur ONTAP pour l'association de liaisons.




==== Prise en charge de l'authentification de liens pour AWS secrets Manager

Vous avez désormais la possibilité d'utiliser les secrets d'AWS secrets Manager pour authentifier les liens afin de ne pas avoir à utiliser les informations d'identification stockées dans l'usine de workloads BlueXP .



==== Assistance de suivi

Tracker fournit désormais des réponses API pour que vous puissiez voir la sortie de l'API REST associée à la tâche.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/monitor-operations.html["Surveiller les opérations avec Tracker"]



==== Validation de la capacité lors de la restauration d'un volume à partir d'une sauvegarde

Lors de la restauration d'un volume à partir d'une sauvegarde, l'usine de workloads BlueXP  détermine si vous disposez de suffisamment de capacité pour la restauration et peut ajouter automatiquement de la capacité de Tier de stockage SSD si ce n'est pas le cas.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/restore-from-backup.html["Restaurer un volume à partir d'une sauvegarde"]



==== Prise en charge d'autres informations d'identification utilisateur ONTAP

L'usine de workloads prend désormais en charge d'autres ensembles d'identifiants ONTAP pour la création de systèmes de fichiers afin de minimiser les risques liés à la sécurité. Au lieu d'utiliser uniquement l'utilisateur fsxadmin, vous pouvez sélectionner un autre ensemble d'informations d'identification ONTAP ou choisir de ne pas fournir de mot de passe aux utilisateurs fsxadmin et vsaadmin.



==== Mise à jour de la terminologie des autorisations

L'interface utilisateur et la documentation de l'usine de charge de travail utilisent désormais « lecture seule » pour faire référence aux autorisations de lecture et « lecture/écriture » pour faire référence aux autorisations d'automatisation.



=== Charges de travail des bases de données



==== Améliorations du tableau de bord

* Des vues multi-comptes et inter-régions sont disponibles lorsque vous naviguez entre les onglets dans la console BlueXP  Workload Factory. Ces nouvelles vues améliorent la gestion, la surveillance et l'optimisation des ressources.
* À partir de la mosaïque *économies potentielles* du tableau de bord, vous pourrez rapidement consulter les économies que vous pourriez réaliser en passant à FSX pour ONTAP à partir d'Amazon Elastic Block Store ou d'Amazon FSX pour serveur de fichiers Windows.




==== Analyse ad hoc disponible pour les configurations de base de données

L'usine de workloads BlueXP  pour les bases de données analyse automatiquement les instances Microsoft SQL Server gérées avec FSX pour le stockage ONTAP en vue d'identifier les problèmes de configuration potentiels. Désormais, en plus de l'acquisition quotidienne, vous pouvez numériser à tout moment.



==== Suppression des dossiers d'évaluation sur place

Après avoir étudié les économies réalisées pour un hôte sur site Microsoft SQL Server, vous avez la possibilité de supprimer l'enregistrement hôte sur site de l'usine de charge de travail BlueXP .



==== Optimisation améliorée



===== Nettoyage des clones

L'évaluation et la correction du nettoyage des clones permettent d'identifier et de gérer les clones anciens et coûteux. Les clones de plus de 60 jours peuvent être actualisés ou supprimés de la console d'usine de la charge de travail BlueXP .



===== Reporter et ignorer l'analyse de la configuration

Certaines configurations peuvent ne pas s'appliquer à vos environnements de base de données. Vous pouvez à présent différer de 30 jours l'analyse d'une configuration donnée ou rejeter l'analyse.



==== Suppression des dossiers d'évaluation sur place

Après avoir étudié les économies réalisées pour un hôte sur site Microsoft SQL Server, vous avez la possibilité de supprimer l'enregistrement hôte sur site de l'usine de charge de travail BlueXP .



==== Mise à jour de la terminologie des autorisations

L'interface utilisateur et la documentation de l'usine de charge de travail utilisent désormais « lecture seule » pour faire référence aux autorisations de lecture et « lecture/écriture » pour faire référence aux autorisations d'automatisation.



=== Workloads VMware



==== Améliorations d'Amazon EC2 migration Advisor

Cette version de la fabrique de workloads BlueXP  pour VMware offre les améliorations suivantes à l'expérience de migration Advisor dans Amazon EC2 :

*Informations sur l'infrastructure de données NetApp en tant que source de données* : la fabrique de workloads se connecte désormais directement aux informations sur l'infrastructure de données NetApp pour collecter des informations sur le déploiement VMware lorsque vous utilisez le collecteur de données EC2 migration Advisor.

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Créez un plan de déploiement pour Amazon EC2 à l'aide du conseiller de migration"]



==== Mise à jour de la terminologie des autorisations

L'interface utilisateur et la documentation de l'usine de charge de travail utilisent désormais « lecture seule » pour faire référence aux autorisations de lecture et « lecture/écriture » pour faire référence aux autorisations d'automatisation.



=== Charges de travail GenAI



==== Prise en charge du connecteur NetApp pour Amazon Q Business

Cette version de GenAI introduit la prise en charge de NetApp Connector pour Amazon Q Business, vous permettant de créer des connecteurs pour Amazon Q Business. Profitez rapidement et facilement de l'assistant IA Amazon Q Business avec moins de configuration initiale qu'en construisant une base de connaissances GenAI pour le socle Amazon.

link:https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html["Créer un connecteur NetApp pour Amazon Q Business"]



==== Prise en charge améliorée des modèles de chat

GenAI prend désormais en charge les modèles de chat supplémentaires suivants pour les bases de connaissances :

* link:https://docs.mistral.ai/getting-started/models/models_overview/["Modèles d'IA Mistral"^]
* link:https://docs.aws.amazon.com/bedrock/latest/userguide/titan-text-models.html["Modèles texte Amazon Titan"^]
* link:https://www.llama.com/docs/model-cards-and-prompt-formats/["Modèles META Llama"^]
* link:https://docs.ai21.com/["Modèles Jamba 1.5"^]
* link:https://docs.cohere.com/docs/the-cohere-platform["Modèles Cohere Command"^]
* link:https://aws.amazon.com/bedrock/deepseek/["Modèles DeepSeek"^]


GenAI prend en charge les modèles de chaque fournisseur pris en charge par Amazon Bedrock : link:https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html["Modèles de base pris en charge dans Amazon Bedrock"^]

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["Créer une base de connaissances GenAI"]



==== Mise à jour de la terminologie des autorisations

L'interface utilisateur et la documentation de l'usine de charge de travail utilisent désormais « lecture seule » pour faire référence aux autorisations de lecture et « lecture/écriture » pour faire référence aux autorisations d'automatisation.



=== Configuration et administration



==== Prise en charge de CloudShell avec remplissage automatique

Lorsque vous utilisez BlueXP  Workload Factory CloudShell, vous pouvez commencer à taper une commande et appuyer sur la touche Tab pour afficher les options disponibles. S'il existe plusieurs possibilités, l'interface de ligne de commande affiche une liste de suggestions. Cette fonction améliore la productivité en réduisant au minimum les erreurs et en accélérant l'exécution des commandes.



==== Mise à jour de la terminologie des autorisations

L'interface utilisateur et la documentation de l'usine de charge de travail utilisent désormais « lecture seule » pour faire référence aux autorisations de lecture et « lecture/écriture » pour faire référence aux autorisations d'automatisation.



=== Charges de travail des constructeurs



==== Mise à jour de la terminologie des autorisations

L'interface utilisateur et la documentation de l'usine de charge de travail utilisent désormais « lecture seule » pour faire référence aux autorisations de lecture et « lecture/écriture » pour faire référence aux autorisations d'automatisation.



== 2025-04-04



=== Charges de travail des bases de données



==== Optimisation améliorée

Lors de l'optimisation de vos environnements de base de données, de nouvelles évaluations d'optimisation, des corrections et l'affichage de plusieurs ressources sont disponibles.



===== Évaluations de résilience

Ces améliorations incluent de nouvelles évaluations de la résilience pour vérifier que les fonctionnalités de redondance des données et de reprise d'activité sont configurées pour vos environnements de base de données.

* Sauvegardes FSX pour ONTAP : analyse si les systèmes de fichiers FSX pour ONTAP qui desservent les volumes de l'instance SQL Server sont configurés avec des sauvegardes FSX pour ONTAP planifiées.
* Réplication interrégionale : vérifie si les systèmes de fichiers FSX pour ONTAP qui servent des instances de Microsoft SQL Server sont configurés avec la réplication interrégionale.




===== Résolution des problèmes de calcul

La correction RSS (Receive Side Scaling) configure RSS pour distribuer le traitement réseau sur plusieurs processeurs et assurer une distribution de charge efficace.



===== Correction locale des snapshots

La correction locale des snapshots définit des règles de snapshot pour les volumes de vos instances Microsoft SQL Server afin de préserver la résilience de vos environnements de base de données en cas de perte de données.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Optimiser les configurations"]



===== Prise en charge de la sélection de plusieurs ressources

Lors de l'optimisation des configurations de base de données, vous pouvez désormais sélectionner des ressources spécifiques au lieu de toutes les ressources.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Optimiser les configurations"]



==== Vue Inventaire améliorée

L'onglet Inventaire de la console d'usine des workloads a été rationalisé de sorte qu'il ne contienne que les serveurs SQL s'exécutant sur Amazon FSX pour NetApp ONTAP. Vous trouverez maintenant des serveurs SQL sur site et s'exécutant sur Amazon Elastic Block Store et Amazon FSX pour Windows File Server dans l'onglet économies Explore.



==== Création rapide disponible pour le déploiement du serveur PostgreSQL

Vous pouvez utiliser cette option de déploiement rapide pour créer un serveur PostgreSQL avec une configuration haute disponibilité et les meilleures pratiques intégrées.

link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["Créez un serveur PostgreSQL en usine de charges de travail BlueXP"]



== 2025-03-30



=== Workloads VMware



==== Améliorations d'Amazon EC2 migration Advisor

Cette version de la fabrique de workloads BlueXP  pour VMware apporte plusieurs améliorations à l'expérience de l'outil de conseil en migration Amazon EC2 :

* *Conseils améliorés d'attribution de volume* : les informations d'affectation de volume des étapes « classifier » et « Package » du conseiller de migration EC2 offrent une meilleure lisibilité et une plus grande facilité d'utilisation. Des informations plus utiles s'affichent sur chaque volume pour vous permettre de mieux identifier les volumes et de déterminer comment les attribuer.
* *Améliorations de l'efficacité du script du collecteur de données* : le script du collecteur de données EC2 migration Advisor optimise l'utilisation du processeur lors de la collecte de données pour les déploiements de machines virtuelles plus petits.


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Créez un plan de déploiement pour Amazon EC2 à l'aide du conseiller de migration"]



=== Configuration et administration



==== CloudShell signale les réponses d'erreur générées par l'IA pour les commandes de l'interface de ligne de commande ONTAP

Lorsque vous utilisez CloudShell, chaque fois que vous exécutez une commande de l'interface de ligne de commande ONTAP et qu'une erreur se produit, vous pouvez obtenir des réponses d'erreur générées par l'IA incluant une description de l'échec, la cause de l'échec et une résolution détaillée.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Utilisez CloudShell"]



==== iam:mise à jour des autorisations SimulatePermissionPolicy

Vous pouvez désormais gérer les `iam:SimulatePrincipalPolicy` autorisations à partir de la console d'usine des charges de travail lorsque vous ajoutez des informations d'identification de compte AWS supplémentaires ou que vous ajoutez une nouvelle fonctionnalité de charge de travail telle que la charge de travail GenAI.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Journal des modifications de référence des autorisations"]



== 2024-12-01



=== Charges de travail des constructeurs



==== Création de la version initiale de la charge de travail

L'usine de charges de travail BlueXP  pour Builders simplifie la consommation et l'accès aux versions logicielles, éliminant ainsi le besoin d'outils ou de scripts personnalisés. Il vous permet de consommer des versions logicielles sous forme de clones instantanés intégrés à Perforce Helix Core comme espace de travail pratique pour vos processus de développement, ce qui vous fait gagner du temps et des ressources.

La version initiale permet de gérer des projets et des espaces de travail, et d'automatiser les actions avec Codebox. Vous pouvez également intégrer Builders à Perforce Helix Core, afin de gérer différentes versions de chaque projet et de passer rapidement de l'une à l'autre.
