---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: 'Découvrez les derniers changements apportés aux charges de travail de l"usine BlueXP .' 
---
= Modifications récentes de l'usine de workloads BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Découvrez les derniers changements apportés aux charges de travail de l'usine BlueXP .



== 03/08/2025



=== Amazon FSX pour NetApp ONTAP



==== Améliorations apportées à l'onglet Relations de réplication

Nous avons ajouté plusieurs nouvelles colonnes au tableau des relations de réplication pour vous donner plus d'informations sur vos relations de réplication dans l'onglet *Relations de réplication*. Le tableau comprend désormais les colonnes suivantes :

* Politique SnapMirror
* Système de fichiers source
* Système de fichiers cible
* État de la relation
* Heure du dernier transfert




==== Améliorations de la protection autonome contre les ransomwares de NetApp avec IA (ARP/AI)

Cette version introduit le terme mis à jour « NetApp Autonomous Ransomware Protection with AI (ARP/AI) » pour mieux refléter l'intégration de l'intelligence artificielle dans nos capacités de protection contre les ransomwares.

De plus, les améliorations suivantes ont été apportées à ARP/AI :

* ARP/AI au niveau du volume : vous pouvez désormais activer ARP/AI au niveau du volume, ce qui vous permet de protéger des volumes spécifiques au sein de vos systèmes de fichiers FSx for ONTAP .
* Création automatique de snapshots : vous pouvez définir la stratégie ARP/AI pour prendre des snapshots automatiques et définir la fréquence à laquelle les snapshots sont pris pour les volumes avec ARP/AI activé, améliorant ainsi votre stratégie de protection des données.
* Instantanés immuables : ARP/AI prend désormais en charge les instantanés immuables, qui ne peuvent pas être supprimés ou modifiés, offrant ainsi une couche de sécurité supplémentaire contre les attaques de ransomware.
* Détection : comprend diverses méthodes de détection telles que le taux de données d'entropie élevé au niveau du volume, le taux de création de fichiers, le taux de renommage de fichiers, le taux de suppression de fichiers et l'analyse comportementale, ainsi qu'une extension de fichier jamais vue auparavant qui aide à détecter les anomalies et les attaques potentielles de ransomware.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["Protégez vos données avec NetApp Autonomous Ransomware Protection with AI (ARP/AI)"]



==== Mises à jour d'analyse bien conçues

Workload Factory analyse désormais vos systèmes de fichiers FSx for ONTAP pour les configurations suivantes :

* Fiabilité des données de rétention à long terme : vérifie si les étiquettes attribuées à la stratégie de snapshot du volume source sont identiques aux étiquettes attribuées à la stratégie de rétention à long terme. Lorsque les étiquettes sont identiques, la réplication des données est fiable entre les volumes source et cible.
* Protection autonome contre les ransomwares NetApp avec IA (ARP/AI) : vérifie si ARP/AI est activé sur vos systèmes de fichiers. Cette fonctionnalité vous aide à détecter et à récupérer des attaques de ransomware.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Affichez l'état bien architecturé de vos systèmes de fichiers FSx for ONTAP"]



==== Supprimer une configuration de l'analyse bien architecturée

Vous pouvez désormais ignorer une ou plusieurs configurations de l’analyse bien architecturée. Cela vous permet d'ignorer les configurations spécifiques que vous ne souhaitez pas aborder pour le moment.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Supprimer une configuration de l'analyse bien architecturée"]



==== Prise en charge de Terraform pour la création de liens

Vous pouvez désormais utiliser Terraform depuis Codebox pour créer un lien d'association avec un système de fichiers FSx pour ONTAP . Cette fonctionnalité est destinée aux utilisateurs qui créent des liens manuellement.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Connectez-vous à un système de fichiers FSX pour ONTAP via un lien Lambda"]



==== Nouvelle prise en charge régionale pour explorer les économies de stockage

Les nouvelles régions suivantes sont désormais prises en charge pour explorer les économies pour Amazon Elastic Block Store (EBS), FSx pour Windows File Server et Elastic File Systems (EFS) :

* Mexique
* Thaïlande




==== Améliorations apportées à la création et à la gestion des partages SMB/CIFS

Vous pouvez désormais créer des partages SMB/CIFS qui pointent vers des répertoires au sein d’un volume. Dans le volume, vous pourrez voir quels partages existent, vers où pointent les partages et les autorisations accordées à des utilisateurs et groupes spécifiques.

Pour les volumes de protection des données, le flux de création d'un partage SMB/CIFS inclut désormais la création d'un chemin de jonction vers le volume à des fins de montage.

link:https://review.docs.netapp.com/us-en/workload-fsx-ontap_grogu-5684-wa-dismiss/manage-cifs-share.html#create-a-cifs-share-for-a-volume["Créer un partage CIFS pour un volume"]



== 2025-06-30



=== Charges de travail des bases de données



==== Prise en charge du service de notification de l'usine de charge de travail BlueXP

Le service de notification de l'usine de charge de travail BlueXP permet à l'usine de charge de travail d'envoyer des notifications au service d'alertes BlueXP ou à une rubrique Amazon SNS. Les notifications envoyées aux alertes BlueXP apparaissent dans le panneau des alertes BlueXP. Lorsque la fabrique de charges de travail publie des notifications dans une rubrique Amazon SNS, les abonnés à cette rubrique (tels que les personnes ou d'autres applications) reçoivent les notifications aux points de terminaison configurés pour cette rubrique (tels que les e-mails ou les SMS).

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Configurer les notifications de l'usine de charge de travail BlueXP"^]

Workload Factory fournit les notifications suivantes pour les bases de données :

* Rapport bien conçu
* Déploiement de l'hôte




==== Amélioration de l'intégration pour l'enregistrement des instances

Workload Factory for Databases a amélioré son processus d'intégration pour l'enregistrement des instances exécutées sur Amazon FSx pour le stockage NetApp ONTAP. Vous pouvez désormais sélectionner des instances en masse pour l'enregistrement. Une fois qu'une instance est enregistrée, vous pouvez créer et gérer les ressources de base de données dans la console de l'usine de charge de travail.

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["Gestion des instances"]



==== Analyse et correction du paramètre de délai d'expiration d'E/S multipath de Microsoft

L'état bien architecturé de vos instances de base de données inclut désormais l'analyse et le correctif pour le paramètre de délai d'expiration Microsoft Multipath I/O (MPIO). Définir ce délai à 60 secondes garantit la connectivité et la stabilité du stockage FSx for ONTAP lors des basculements. Si le paramètre MPIO n'est pas correctement défini, Workload Factory fournira un correctif pour définir ce délai à 60 secondes.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implémenter des configurations de base de données bien architecturées dans Workload Factory"]



==== Améliorations des graphiques dans l'inventaire des instances

À partir de l'écran d'inventaire des instances, divers graphiques d'utilisation des ressources tels que le débit et les IOPS affichent désormais 7 jours de données afin que vous puissiez surveiller plus efficacement les performances des nœuds SQL à partir de la console de l'usine de charge de travail. Les indicateurs de performance collectés auprès des nœuds SQL sont enregistrés dans Amazon CloudWatch et peuvent être utilisés pour Logs Insights ou intégrés à d'autres services d'analyse de votre environnement.

À partir des onglets Instances et Bases de données de l'inventaire, nous avons amélioré la description et la visualisation pour la protection.



==== Prise en charge de l'authentification Windows dans Workload Factory

Désormais, Workload Factory prend en charge l'authentification SQL Server à l'aide d'utilisateurs authentifiés Windows pour enregistrer des instances et bénéficier des fonctionnalités de gestion.

link:https://docs.netapp.com/us-en/workload-databases/register-instance.html["Enregistrer des instances dans la fabrique de charges de travail pour les bases de données"]



== 2025-06-29



=== Amazon FSX pour NetApp ONTAP



==== Prise en charge du service de notification de l'usine de charge de travail BlueXP

Le service de notification de l'usine de charge de travail BlueXP permet à l'usine de charge de travail d'envoyer des notifications au service d'alertes BlueXP ou à une rubrique Amazon SNS. Les notifications envoyées aux alertes BlueXP apparaissent dans le panneau des alertes BlueXP. Lorsque la fabrique de charges de travail publie des notifications dans une rubrique Amazon SNS, les abonnés à cette rubrique (tels que les personnes ou d'autres applications) reçoivent les notifications aux points de terminaison configurés pour cette rubrique (tels que les e-mails ou les SMS).

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Configurer les notifications de l'usine de charge de travail BlueXP"^]



==== Améliorations du tableau de bord de stockage

Le tableau de bord Stockage de la console Workload Factory inclut de nouvelles cartes pour les opportunités d'économies. La carte en haut du tableau de bord affiche le nombre d'opportunités d'économies pour les environnements de stockage exécutés sur Amazon Elastic Block Store (EBS), Amazon FSx for Windows File Server et Amazon Elastic File Systems (EFS). En bas du tableau de bord, trois nouvelles cartes affichent les opportunités d'économies par service de stockage Amazon : EBS, FSx for Windows File Server et EFS. À partir de chaque carte, vous pouvez explorer les opportunités d'économies plus en détail.

À partir de la carte de couverture de protection et de la carte d'intégrité des relations de réplication de FSx for ONTAP, vous pouvez vérifier la présence de volumes partiellement protégés dans vos systèmes de fichiers FSx for ONTAP et identifier les problèmes liés aux relations de réplication. Dans les deux cas, vous pouvez prendre des mesures pour résoudre les problèmes.



==== Améliorations de l'onglet Volume

L'onglet Volumes de la console Workload Factory a été amélioré pour offrir une vue plus complète de vos systèmes de fichiers FSx for ONTAP. Ces améliorations incluent de nouvelles cartes pour la capacité SSD, le pool de capacité et la protection autonome contre les ransomwares NetApp avec IA (ARP/AI). Ces cartes résument l'utilisation de la capacité et la protection ARP/AI pour tous les volumes du système de fichiers.



==== Prise en charge des systèmes de fichiers Amazon FSX pour NetApp ONTAP de deuxième génération

Workload Factory prend désormais en charge les systèmes de fichiers Amazon FSx for NetApp ONTAP de deuxième génération. Vous pouvez créer, gérer et surveiller des systèmes de fichiers de deuxième génération dans la console Workload Factory. Toutes les nouvelles régions commerciales sont prises en charge.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Créer un système de fichiers de deuxième génération dans Workload Factory"]



==== Prise en charge du volume FlexVol pour rééquilibrer la capacité du volume

Les volumes FlexVol sont détectables dans la console Workload Factory. Vous pouvez vérifier l'équilibre de vos volumes FlexVol et les rééquilibrer pour redistribuer la capacité lorsque des déséquilibres apparaissent au fil du temps, dus à l'ajout de nouveaux fichiers et à leur croissance.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/rebalance-volume.html["Rééquilibrer la capacité d'un volume FlexVol"]



==== Mise à jour de la terminologie

Le terme « Autonomous Ransomware Protection » (ARP) a été mis à jour en « NetApp Autonomous Ransomware Protection with AI » (ARP/AI) dans la console de l'usine de charge de travail.



==== ARP/AI activé par défaut pour les nouveaux volumes

Lorsque vous créez un volume dans la console Workload Factory, la protection autonome contre les ransomwares NetApp avec IA (ARP/AI) est activée par défaut si le système de fichiers dispose d'une stratégie ARP/AI. Cela signifie que le volume est automatiquement protégé contre les attaques de ransomware grâce à des fonctionnalités de détection et de réponse basées sur l'IA.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Créer un volume dans la fabrique de charges de travail"]



==== Prise en charge de la réplication pour les fichiers immuables

Workload Factory prend en charge la réplication de volumes immuables d'un système FSx for ONTAP vers un autre système de fichiers FSx for ONTAP afin de protéger les données critiques contre toute suppression accidentelle ou attaque malveillante comme les rançongiciels. Le volume cible et son système de fichiers hôte sont immuables, ou verrouillés, et les données du système de fichiers cible ne peuvent être ni modifiées ni supprimées avant la fin de la période de conservation.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Apprenez à créer une relation de réplication"]



==== Gérer le rôle d'exécution et les autorisations IAM lors de la création du lien

Vous pouvez désormais gérer le rôle d'exécution IAM et la politique d'autorisations associée en créant un lien dans la console Workload Factory. Un lien établit la connectivité entre votre compte Workload Factory et un ou plusieurs systèmes de fichiers FSx for ONTAP. Vous disposez de deux options pour attribuer le rôle d'exécution IAM et les autorisations associées : automatiquement ou par l'utilisateur. La gestion du rôle d'exécution et de la politique d'autorisations associée dans Workload Factory vous évite d'avoir recours à du code tiers.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Connectez-vous à un système de fichiers FSX pour ONTAP via un lien Lambda"]



=== Workloads VMware



==== Présentation de la prise en charge du conseiller de migration pour Amazon Elastic VMware Service

L'usine de charges de travail BlueXP pour VMware prend désormais en charge Amazon Elastic VMware Service. Grâce à l'assistant de migration, vous pouvez migrer rapidement vos charges de travail VMware sur site vers Amazon Elastic VMware Service. Vous optimisez ainsi vos coûts et bénéficiez d'un meilleur contrôle sur votre environnement VMware sans avoir à refactoriser ou à repenser la plateforme de vos applications.

https://docs.netapp.com/us-en/workload-vmware/launch-migration-advisor-evs-manual.html["Créer un plan de déploiement pour Amazon EVS à l'aide du conseiller de migration"]



=== Charges de travail GenAI



==== Prise en charge des sources de données hébergées sur des systèmes de fichiers NFS/SMB génériques

Vous pouvez désormais ajouter une source de données à partir d'un partage SMB ou NFS générique. Cela vous permet d'inclure des fichiers stockés sur des volumes hébergés par des systèmes de fichiers autres qu'Amazon FSx pour NetApp ONTAP.

https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["Ajouter des sources de données à une base de connaissances"]

https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html#add-data-sources-to-the-connector["Ajouter des sources de données à un connecteur"]



=== Configuration et administration



==== Mise à jour des autorisations pour les bases de données

L'autorisation suivante est désormais disponible en mode _lecture seule_ pour les bases de données :  `cloudwatch:GetMetricData` .

https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Journal des modifications de référence des autorisations"]



==== Prise en charge du service de notification de l'usine de charge de travail BlueXP

Le service de notification de l'usine de charge de travail BlueXP permet à l'usine de charge de travail d'envoyer des notifications au service d'alertes BlueXP ou à une rubrique Amazon SNS. Les notifications envoyées aux alertes BlueXP apparaissent dans le panneau des alertes BlueXP. Lorsque la fabrique de charges de travail publie des notifications dans une rubrique Amazon SNS, les abonnés à cette rubrique (tels que les personnes ou d'autres applications) reçoivent les notifications aux points de terminaison configurés pour cette rubrique (tels que les e-mails ou les SMS).

https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Configurer les notifications de l'usine de charge de travail BlueXP"]



== 2025-06-16



=== Charges de travail des constructeurs



==== Prise en charge du clonage

Vous pouvez désormais cloner un projet dans la Workload Factory de BlueXP pour Builders. Lorsque vous clonez un projet, Builders crée un nouveau projet à partir d'un snapshot, avec la même configuration que l'original. Le clonage est utile pour créer rapidement des projets similaires ou à des fins de test. Vous pouvez monter le nouveau clone de projet en suivant les instructions de Builders.

https://docs.netapp.com/us-en/workload-builders/version-projects.html["Gérer les versions de l'usine de charge de travail BlueXP pour les projets Builders"]



== 2025-06-08



=== Amazon FSX pour NetApp ONTAP



==== Nouvelle analyse et assistance bien conçues pour résoudre les problèmes

La gestion automatique de la capacité des systèmes de fichiers FSx for ONTAP est désormais incluse en tant qu'analyse de configuration dans le tableau de bord d'état bien architecturé.

De plus, Workload Factory prend désormais en charge la résolution des problèmes de configuration suivants :

* Seuil de capacité SSD
* Tiering des données
* Snapshots locaux planifiés
* FSx pour les sauvegardes ONTAP
* Réplication des données à distance
* Fonctionnalités d'efficacité du stockage
* Gestion automatique de la capacité


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Résoudre les problèmes de configuration"]



== 2025-06-03



=== Charges de travail des bases de données



==== Détection PostgreSQL et Oracle

Vous pouvez désormais découvrir les instances exécutant des bases de données PostgreSQL et des déploiements de bases de données Oracle sur votre compte AWS depuis la console Workload Factory. Les instances découvertes apparaîtront dans l'inventaire des bases de données.



==== Terminologie « Optimisation » mise à jour

Auparavant appelée « Optimisation », Workload Factory utilise désormais « problèmes bien architecturés » et « état bien architecturé » pour décrire l'analyse des configurations de base de données et « correctif » pour décrire la correction des opportunités d'amélioration des configurations de base de données afin de répondre aux recommandations des meilleures pratiques.

link:https://docs.netapp.com/us-en/workload-databases/optimize-overview.html["Analyse de configuration pour les environnements de base de données dans Workload Factory"]



==== Intégration améliorée pour les instances

Au lieu des termes « non détecté », « non géré » ou « géré » pour la gestion des instances, Workload Factory utilise désormais « registre » pour l'intégration des instances. Le nouveau processus d'enregistrement inclut l'authentification et la préparation des instances afin que vous puissiez créer, surveiller, analyser et corriger les ressources dans vos configurations de base de données depuis la console Workload Factory. L'étape de préparation du processus d'enregistrement indique si vos instances sont prêtes à être gérées.

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["Gestion des instances"]



=== Charges de travail GenAI



==== Tracker disponible pour les opérations de surveillance et de suivi

La fonctionnalité de surveillance Tracker est désormais disponible dans GenAI. Vous pouvez utiliser Tracker pour surveiller et suivre la progression et l'état des opérations en attente, en cours et terminées, consulter les détails des tâches et sous-tâches opérationnelles, diagnostiquer les problèmes ou les échecs, modifier les paramètres des opérations ayant échoué et relancer les opérations ayant échoué.

link:https://docs.netapp.com/us-en/workload-genai/general/monitor-operations.html["Surveillez les opérations de charge de travail avec Tracker dans l'usine de charge de travail BlueXP"]



==== Choisir un modèle de reranker pour une base de connaissances

Vous pouvez désormais améliorer la pertinence des résultats de requêtes reclassés en sélectionnant un modèle de reranking spécifique à utiliser avec une base de connaissances. GenAI prend en charge les modèles Cohere Rerank et Amazon Rerank.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["Créer une base de connaissances GenAI"]



== 2025-05-04



=== Charges de travail des bases de données



==== Améliorations du tableau de bord

* Des vues multi-comptes et inter-régions sont disponibles lorsque vous naviguez entre les onglets dans la console BlueXP  Workload Factory. Ces nouvelles vues améliorent la gestion, la surveillance et l'optimisation des ressources.
* À partir de la mosaïque *économies potentielles* du tableau de bord, vous pourrez rapidement consulter les économies que vous pourriez réaliser en passant à FSX pour ONTAP à partir d'Amazon Elastic Block Store ou d'Amazon FSX pour serveur de fichiers Windows.




==== Analyse ad hoc disponible pour les configurations de base de données

L'usine de workloads BlueXP  pour les bases de données analyse automatiquement les instances Microsoft SQL Server gérées avec FSX pour le stockage ONTAP en vue d'identifier les problèmes de configuration potentiels. Désormais, en plus de l'acquisition quotidienne, vous pouvez numériser à tout moment.



==== Suppression des dossiers d'évaluation sur place

Après avoir étudié les économies réalisées pour un hôte sur site Microsoft SQL Server, vous avez la possibilité de supprimer l'enregistrement hôte sur site de l'usine de charge de travail BlueXP .



==== Optimisation améliorée



===== Nettoyage des clones

L'évaluation et la correction du nettoyage des clones permettent d'identifier et de gérer les clones anciens et coûteux. Les clones de plus de 60 jours peuvent être actualisés ou supprimés de la console d'usine de la charge de travail BlueXP .



===== Reporter et ignorer l'analyse de la configuration

Certaines configurations peuvent ne pas s'appliquer à vos environnements de base de données. Vous pouvez à présent différer de 30 jours l'analyse d'une configuration donnée ou rejeter l'analyse.



==== Suppression des dossiers d'évaluation sur place

Après avoir étudié les économies réalisées pour un hôte sur site Microsoft SQL Server, vous avez la possibilité de supprimer l'enregistrement hôte sur site de l'usine de charge de travail BlueXP .



==== Mise à jour de la terminologie des autorisations

L'interface utilisateur et la documentation de l'usine de charge de travail utilisent désormais « lecture seule » pour faire référence aux autorisations de lecture et « lecture/écriture » pour faire référence aux autorisations d'automatisation.



=== Workloads VMware



==== Améliorations d'Amazon EC2 migration Advisor

Cette version de la fabrique de workloads BlueXP  pour VMware offre les améliorations suivantes à l'expérience de migration Advisor dans Amazon EC2 :

*Informations sur l'infrastructure de données NetApp en tant que source de données* : la fabrique de workloads se connecte désormais directement aux informations sur l'infrastructure de données NetApp pour collecter des informations sur le déploiement VMware lorsque vous utilisez le collecteur de données EC2 migration Advisor.

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Créez un plan de déploiement pour Amazon EC2 à l'aide du conseiller de migration"]



==== Mise à jour de la terminologie des autorisations

L'interface utilisateur et la documentation de l'usine de charge de travail utilisent désormais « lecture seule » pour faire référence aux autorisations de lecture et « lecture/écriture » pour faire référence aux autorisations d'automatisation.



=== Charges de travail GenAI



==== Prise en charge du connecteur NetApp pour Amazon Q Business

Cette version de GenAI introduit la prise en charge de NetApp Connector pour Amazon Q Business, vous permettant de créer des connecteurs pour Amazon Q Business. Profitez rapidement et facilement de l'assistant IA Amazon Q Business avec moins de configuration initiale qu'en construisant une base de connaissances GenAI pour le socle Amazon.

link:https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html["Créer un connecteur NetApp pour Amazon Q Business"]



==== Prise en charge améliorée des modèles de chat

GenAI prend désormais en charge les modèles de chat supplémentaires suivants pour les bases de connaissances :

* link:https://docs.mistral.ai/getting-started/models/models_overview/["Modèles d'IA Mistral"^]
* link:https://docs.aws.amazon.com/bedrock/latest/userguide/titan-text-models.html["Modèles texte Amazon Titan"^]
* link:https://www.llama.com/docs/model-cards-and-prompt-formats/["Modèles META Llama"^]
* link:https://docs.ai21.com/["Modèles Jamba 1.5"^]
* link:https://docs.cohere.com/docs/the-cohere-platform["Modèles Cohere Command"^]
* link:https://aws.amazon.com/bedrock/deepseek/["Modèles DeepSeek"^]


GenAI prend en charge les modèles de chaque fournisseur pris en charge par Amazon Bedrock : link:https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html["Modèles de base pris en charge dans Amazon Bedrock"^]

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["Créer une base de connaissances GenAI"]



==== Mise à jour de la terminologie des autorisations

L'interface utilisateur et la documentation de l'usine de charge de travail utilisent désormais « lecture seule » pour faire référence aux autorisations de lecture et « lecture/écriture » pour faire référence aux autorisations d'automatisation.



=== Configuration et administration



==== Prise en charge de CloudShell avec remplissage automatique

Lorsque vous utilisez BlueXP  Workload Factory CloudShell, vous pouvez commencer à taper une commande et appuyer sur la touche Tab pour afficher les options disponibles. S'il existe plusieurs possibilités, l'interface de ligne de commande affiche une liste de suggestions. Cette fonction améliore la productivité en réduisant au minimum les erreurs et en accélérant l'exécution des commandes.



==== Mise à jour de la terminologie des autorisations

L'interface utilisateur et la documentation de l'usine de charge de travail utilisent désormais « lecture seule » pour faire référence aux autorisations de lecture et « lecture/écriture » pour faire référence aux autorisations d'automatisation.



=== Charges de travail des constructeurs



==== Mise à jour de la terminologie des autorisations

L'interface utilisateur et la documentation de l'usine de charge de travail utilisent désormais « lecture seule » pour faire référence aux autorisations de lecture et « lecture/écriture » pour faire référence aux autorisations d'automatisation.



== 2025-03-30



=== Workloads VMware



==== Améliorations d'Amazon EC2 migration Advisor

Cette version de la fabrique de workloads BlueXP  pour VMware apporte plusieurs améliorations à l'expérience de l'outil de conseil en migration Amazon EC2 :

* *Conseils améliorés d'attribution de volume* : les informations d'affectation de volume des étapes « classifier » et « Package » du conseiller de migration EC2 offrent une meilleure lisibilité et une plus grande facilité d'utilisation. Des informations plus utiles s'affichent sur chaque volume pour vous permettre de mieux identifier les volumes et de déterminer comment les attribuer.
* *Améliorations de l'efficacité du script du collecteur de données* : le script du collecteur de données EC2 migration Advisor optimise l'utilisation du processeur lors de la collecte de données pour les déploiements de machines virtuelles plus petits.


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Créez un plan de déploiement pour Amazon EC2 à l'aide du conseiller de migration"]



=== Configuration et administration



==== CloudShell signale les réponses d'erreur générées par l'IA pour les commandes de l'interface de ligne de commande ONTAP

Lorsque vous utilisez CloudShell, chaque fois que vous exécutez une commande de l'interface de ligne de commande ONTAP et qu'une erreur se produit, vous pouvez obtenir des réponses d'erreur générées par l'IA incluant une description de l'échec, la cause de l'échec et une résolution détaillée.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Utilisez CloudShell"]



==== iam:mise à jour des autorisations SimulatePermissionPolicy

Vous pouvez désormais gérer les `iam:SimulatePrincipalPolicy` autorisations à partir de la console d'usine des charges de travail lorsque vous ajoutez des informations d'identification de compte AWS supplémentaires ou que vous ajoutez une nouvelle fonctionnalité de charge de travail telle que la charge de travail GenAI.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Journal des modifications de référence des autorisations"]



== 2024-12-01



=== Charges de travail des constructeurs



==== Création de la version initiale de la charge de travail

L'usine de charges de travail BlueXP  pour Builders simplifie la consommation et l'accès aux versions logicielles, éliminant ainsi le besoin d'outils ou de scripts personnalisés. Il vous permet de consommer des versions logicielles sous forme de clones instantanés intégrés à Perforce Helix Core comme espace de travail pratique pour vos processus de développement, ce qui vous fait gagner du temps et des ressources.

La version initiale permet de gérer des projets et des espaces de travail, et d'automatiser les actions avec Codebox. Vous pouvez également intégrer Builders à Perforce Helix Core, afin de gérer différentes versions de chaque projet et de passer rapidement de l'une à l'autre.
