---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for ontap, databases, genai, vmware' 
summary: Découvrez les derniers changements apportés aux charges de travail de BlueXP  Workload Factory. 
---
= Changements récents dans BlueXP  Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Découvrez les derniers changements apportés aux charges de travail de BlueXP  Workload Factory.



== 4 août 2024



=== Amazon FSX pour NetApp ONTAP



==== Prise en charge de Terraform

Vous pouvez désormais utiliser Terraform à partir de Codebox pour déployer des systèmes de fichiers et des machines virtuelles de stockage.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Créez un système de fichiers"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-storage-vm.html["Créez une machine virtuelle de stockage"]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["Utiliser Terraform à partir de Codebox"^]




==== Recommandations de débit et d'IOPS dans le calculateur de stockage

Le calculateur de stockage fait des recommandations de configuration de système de fichiers FSX pour ONTAP pour le débit et les IOPS en fonction des bonnes pratiques AWS, qui vous guide de façon optimale pour votre sélection.



=== Configuration et administration



==== Prise en charge de Terraform

Terraform est pris en charge pour le déploiement du système de fichiers Amazon FSX pour NetApp ONTAP et la création de machines virtuelles de stockage. Le guide d'installation et d'administration contient maintenant des instructions sur l'utilisation de Terraform à partir de la Codebox.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["Utiliser Terraform à partir de Codebox"^]



== 7 juillet 2024



=== Amazon FSX pour NetApp ONTAP



==== Version initiale de Workload Factory pour Amazon FSX for NetApp ONTAP

Amazon FSX pour NetApp ONTAP est désormais disponible dans Workload Factory.



=== Configuration et administration



==== Version initiale de Workload Factory

BlueXP Workload Factory pour AWS est une plateforme puissante de gestion du cycle de vie conçue pour vous aider à optimiser vos workloads à l'aide des systèmes de fichiers Amazon FSX pour NetApp ONTAP. Parmi les charges de travail pouvant être rationalisées à l'aide de Workload Factory et FSX pour ONTAP figurent les bases de données, les migrations VMware vers VMware Cloud sur AWS, les chatbots d'IA, etc.
