---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: Découvrez les modifications les plus récentes apportées aux charges de travail qui font partie de NetApp Workload Factory. 
---
= Modifications récentes dans NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Découvrez les modifications les plus récentes apportées aux charges de travail qui font partie de NetApp Workload Factory.



== 06 avril 2026



=== Amazon FSX pour NetApp ONTAP



==== Mises à jour d'analyse bien conçues

Workload Factory analyse vos systèmes de fichiers Amazon FSx for ONTAP pour les *volumes NAS inactifs*. L'analyse de configuration identifie les volumes NAS qui ne sont pas activement utilisés et recommande des actions pour optimiser l'utilisation du stockage et réduire les coûts.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Mettre en œuvre des systèmes de fichiers FSx for ONTAP bien architecturés"]



==== Fonctionnalité de table de journal pour les points d'accès S3

La fonctionnalité Journal table permet de gérer le stockage d'objets S3 de FSx ONTAP à grande échelle, facilitant ainsi l'audit des événements d'accès utilisateur et des opérations sur les objets dans vos compartiments. Avec Workload Factory, vous pouvez configurer des analyses automatiques de vos compartiments et tables S3 afin de conserver un historique des événements, affichant tous les objets, leurs détails et les actions des utilisateurs.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/setup-journal-table.html["Configurez l'infrastructure de la table de journalisation pour NetApp Workload Factory"]



==== Prise en charge de la gestion des igroups existants

Workload Factory prend en charge la gestion des igroups existants. Vous pouvez ajouter ou supprimer des périphériques de blocs et des initiateurs hôtes afin de garantir la livraison de votre charge de travail déployée dans les délais impartis.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-storage.html["Gérez le stockage bloc dans NetApp Workload Factory"]



==== Prise en charge de la spécification de l'agrégat pour les volumes FlexVol

Workload Factory permet de créer des volumes FlexVol sur un agrégat choisi. Cela vous permet de répartir la charge de capacité et de performance sur l'ensemble des ressources du système de fichiers.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Créez un FlexVol volume dans NetApp Workload Factory"]



=== Charges de travail des bases de données



==== Analyse bien architecturée pour Oracle

L'analyse bien architecturée inclut les nouvelles configurations suivantes pour Oracle :

* *Mises à jour critiques d'Oracle* : évalue les correctifs de sécurité manquants pour les installations de bases de données autogérées Oracle prises en charge.
* *Réplication interrégionale* : vérifie si la réplication interrégionale (CRR) est activée pour vos systèmes de fichiers FSx for ONTAP servant des bases de données Oracle.
* *Instantanés cohérents au niveau des applications* : vérifie si la base de données Oracle est protégée par des instantanés cohérents au niveau des applications avec NetApp SnapCenter.


link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implémenter des configurations de base de données bien architecturées dans Workload Factory"]



==== Évaluation ponctuelle pour Oracle

Workload Factory propose désormais une évaluation ponctuelle pour analyser la configuration de vos déploiements de bases de données Oracle, à tout moment : nouveaux déploiements, post-migration, dépannage, etc. Vous recevrez des recommandations pour vous aider à optimiser vos configurations de déploiement et à vous conformer aux bonnes pratiques. C'est l'occasion d'utiliser la fonctionnalité bien architecturée sans vous engager pleinement dans le processus de configuration. Vous pouvez évaluer vos bases de données sans stocker d'identifiants dans Workload Factory, sans enregistrer de ressources de base de données ni configurer de connexions externes.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Effectuez une évaluation ponctuelle de vos déploiements de bases de données Oracle"]



==== Amélioration des économies pour plusieurs bases de données Oracle

Nous avons amélioré l'analyse des économies pour Oracle afin de fournir une solution de stockage consolidée pour plusieurs bases de données Oracle sur site sur un seul système de fichiers FSx for ONTAP. Cette consolidation optimise les coûts de stockage en réduisant le nombre de systèmes de fichiers nécessaires pour plusieurs bases de données, ce qui conduit à une amélioration des économies.

link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html#explore-savings-for-detected-hosts["Découvrez les économies pour les bases de données détectées sur Oracle sur site"]



=== Configuration et administration



==== Nouvelle notification pour le stockage

Le service de notification NetApp Workload Factory inclut la notification pour NetApp Autonomous Ransomware Protection with AI (ARP/AI) pour le stockage.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Notifications pour NetApp Workload Factory"]



== 09 mars 2026



=== Workloads VMware



==== Présentation de la prise en charge de l'assistant de migration pour Google Cloud VMware Engine

NetApp Workload Factory prend désormais en charge Google Cloud VMware Engine. Vous pouvez migrer vos charges de travail VMware sur site vers Google Cloud VMware Engine en utilisant Google Cloud NetApp Volumes comme datastores NFS externes, optimisant les coûts et permettant un meilleur contrôle de votre environnement VMware sans avoir à refactoriser ni à replatformer vos applications.

L'assistant de migration Google Cloud VMware Engine fournit :

* Dimensionnement et conception automatisés des clusters Google Cloud VMware Engine avec prise en charge des types de nœuds VE1 et VE2
* Optimisation de la disposition des machines virtuelles entre les datastores internes vSAN et les datastores NFS externes Google Cloud NetApp Volumes.
* Comparaison détaillée des coûts et analyse du coût total de possession (TCO) entre les configurations utilisant uniquement vSAN et celles optimisées par Google Cloud NetApp Volumes.
* Prise en charge des niveaux de service Standard, Premium et Extreme de Google Cloud NetApp Volumes.
* Déploiement d'infrastructure en tant que code avec Terraform pour un provisionnement automatisé.




== 02 mars 2026



=== Charges de travail des bases de données



==== Évaluation ponctuelle pour SQL Server

Workload Factory propose désormais une évaluation ponctuelle pour analyser la configuration de vos déploiements de bases de données SQL Server à tout moment : nouveaux déploiements, post-migration, dépannage, etc. Vous recevrez des recommandations pour vous aider à optimiser vos configurations de déploiement et à vous conformer aux bonnes pratiques. C'est l'occasion d'utiliser la fonctionnalité bien architecturée sans vous engager pleinement dans le processus de configuration. Vous pouvez évaluer vos bases de données sans stocker d'identifiants dans Workload Factory, sans enregistrer de ressources de base de données ni configurer de connexions externes.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Effectuez une évaluation ponctuelle de vos déploiements de base de données"]



==== Prise en charge de l'enregistrement des groupes de disponibilité Always On sur Microsoft SQL Server et de Data Guard sur Oracle

Vous pouvez désormais découvrir et enregistrer des instances Microsoft SQL Server avec le modèle de déploiement Always On availability group (AOAG) et des bases de données Oracle avec le modèle de déploiement Data Guard dans la charge de travail Bases de données de NetApp Workload Factory. Cette amélioration permet une meilleure gestion des ressources SQL Server et Oracle au sein de la console Workload Factory.

Après avoir enregistré vos instances AOAG et vos bases de données Data Guard, vous pouvez profiter des différentes fonctionnalités dans NetApp Workload Factory for Databases, telles que la consultation des détails des ressources et l'analyse des journaux d'erreurs.

Workload Factory for Databases prend également en charge l'analyse bien architecturée des instances Microsoft SQL Server avec le modèle de déploiement AOAG. Vous pouvez analyser les configurations de vos instances SQL Server dans un groupe de disponibilité et recevoir des recommandations pour optimiser vos configurations de déploiement et vous conformer aux bonnes pratiques. Enregistrez vos instances AOAG pour activer cette fonctionnalité.

link:https://docs.netapp.com/us-en/workload-databases/register-instance.html#register-a-sql-server-instance["Enregistrez les ressources dans NetApp Workload Factory for Databases"]



==== Analyse bien architecturée pour Oracle

L'analyse bien conçue inclut les *correctifs du système d'exploitation* pour Oracle afin de vérifier si vous disposez des derniers correctifs sur le système d'exploitation et vous indiquer comment les installer.

De plus, l'analyse d'architecture optimisée pour Oracle vous avertit lorsqu'une configuration, comme l'agencement du stockage, a des dépendances avec d'autres configurations. La notification vous indique quelles actions entreprendre pour optimiser les configurations liées afin que toutes les recommandations que nous fournissons soient optimales.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implémenter des configurations de base de données bien architecturées dans Workload Factory"]



==== Analyse des coûts et planification de la migration des environnements de base de données Oracle sur site

Workload Factory for Databases analyse désormais et vous aide à planifier la migration de la base de données Oracle sur site vers Amazon FSx for NetApp ONTAP. Vous pouvez utiliser le calculateur d'économies pour estimer le coût d'exécution de votre environnement de base de données Oracle sur site dans le cloud et consulter les recommandations pour migrer votre environnement de base de données sur site vers le cloud.

link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html["Explorez les économies pour les environnements de base de données sur site"]



==== Nouveau signet Ask Me disponible dans Workload Factory

Nous avons ajouté un nouveau raccourci Ask Me sur chaque écran de la console Workload Factory. Cette amélioration vous permet d'accéder plus facilement et plus rapidement à Ask Me chaque fois que vous avez besoin d'aide. Ask Me est notre assistant IA, qui vous permet de poser des questions sur vos propres environnements de charge de travail, d'obtenir des informations personnalisées directement à partir de votre environnement et de consulter les conversations précédentes.

Vous pouvez ouvrir Ask Me depuis n'importe quelle page en cliquant sur le nouveau signet. Cela lance Ask Me dans un panneau latéral sans interrompre votre travail en cours et offre des explications et des recommandations rapides en rapport avec ce que vous faites actuellement.

link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html#features["En savoir plus sur Ask Me"^]



== 01 mars 2026



=== Amazon FSX pour NetApp ONTAP



==== Mises à jour d'analyse bien conçues

Workload Factory analyse vos systèmes de fichiers FSx pour ONTAP pour les configurations suivantes :

* Capacité SSD sous-utilisée : vérifie si le niveau de capacité SSD est sous-utilisé et recommande de réduire la capacité SSD pour optimiser les coûts.
* Planifiez les sauvegardes de volumes : NetApp Workload Factory améliore la recommandation de configuration et ajoute des options pour activer la sauvegarde FSx for ONTAP ou AWS Backup. FSx for ONTAP backup applique une stratégie par défaut à tous les volumes d'un système de fichiers, créant des sauvegardes quotidiennes conservées jusqu'à 90 jours. AWS Backup vous permet de choisir des périodes de rétention différentes pour chaque volume du plan de sauvegarde.




==== NetApp Workload Factory prend en charge les cas d'utilisation de l'IA et du ML pour la réplication

Workload Factory prend en charge la réplication des données ONTAP sur site vers Amazon FSx for NetApp ONTAP et la création de points d'accès S3 pour les services AWS Artificial Intelligence (AI) et machine learning (ML) afin d'accélérer les flux de travail AI/ML.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Répliquer les données sur site pour les cas d'utilisation de l'IA et du ML"]



==== Modification des points d'accès S3 existants

Vous pouvez modifier l'utilisateur et le type d'utilisateur d'un point d'accès S3 associé à un volume. Vous pouvez également activer ou désactiver les métadonnées pour le point d'accès.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/edit-s3-access-points.html["Modifier les points d'accès S3 dans NetApp Workload Factory"]



==== Ajout d'un schéma de stockage bloc

Si vous utilisez le stockage bloc, vous pouvez consulter le schéma de stockage bloc pour visualiser comment les périphériques de stockage bloc se connectent aux nœuds et aux igroups. Le schéma vous aide à comprendre et à gérer votre stockage bloc.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-storage.html["Gérez le stockage bloc dans NetApp Workload Factory"]



==== Mise à jour de la fonction de gestion automatique de la capacité

Cette mise à jour divise la fonctionnalité en deux fonctionnalités distinctes : gestion automatique de la capacité et notifications de capacité.

La gestion de la capacité ajoute ou supprime automatiquement de la capacité du système de fichiers afin de maintenir des performances optimales. Parmi les nouvelles options figurent les modes incrémental et adaptatif. En mode incrémental, le système augmente la capacité d’un montant fixe à certains seuils ; en mode adaptatif, il utilise des données historiques pour prédire et ajuster la capacité.

Les notifications de capacité vous alertent à chaque modification de capacité et lorsque les systèmes de fichiers atteignent les limites définies, afin que vous puissiez gérer le stockage avant que des problèmes ne surviennent.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html["Découvrez la gestion automatique de la capacité et les notifications de capacité dans NetApp Workload Factory"]



==== Nouveau signet Ask Me disponible dans Workload Factory

Nous avons ajouté un nouveau raccourci Ask Me sur chaque écran de la console Workload Factory. Cette amélioration vous permet d'accéder plus facilement et plus rapidement à Ask Me dès que vous avez besoin d'aide. Ask Me est notre assistant IA. Vous pouvez poser des questions sur vos environnements de charge de travail, obtenir des informations personnalisées et consulter les conversations précédentes.

Vous pouvez ouvrir Ask Me depuis n'importe quelle page en cliquant sur le nouveau signet. Cela lance Ask Me dans un panneau latéral sans interrompre votre travail en cours et offre des explications et des recommandations rapides en rapport avec ce que vous faites actuellement.

link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html#features["En savoir plus sur Ask Me"^]



=== Workloads VMware



==== Nouveau signet Ask Me disponible dans Workload Factory

Nous avons ajouté un nouveau raccourci Ask Me sur chaque écran de la console Workload Factory. Cette amélioration vous permet d'accéder plus facilement et plus rapidement à Ask Me chaque fois que vous avez besoin d'aide. Ask Me est notre assistant IA, qui vous permet de poser des questions sur vos propres environnements de charge de travail, d'obtenir des informations personnalisées directement à partir de votre environnement et de consulter les conversations précédentes.

Vous pouvez ouvrir Ask Me depuis n'importe quelle page en cliquant sur le nouveau signet. Cela lance Ask Me dans un panneau latéral sans interrompre votre travail en cours et offre des explications et des recommandations rapides en rapport avec ce que vous faites actuellement.

link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html#features["En savoir plus sur Ask Me"^]



=== Configuration et administration



==== Nouveau signet Ask Me disponible dans Workload Factory

Nous avons ajouté un nouveau raccourci Ask Me sur chaque écran de la console Workload Factory. Cette amélioration vous permet d'accéder plus facilement et plus rapidement à Ask Me chaque fois que vous avez besoin d'aide. Ask Me est notre assistant IA, qui vous permet de poser des questions sur vos propres environnements de charge de travail, d'obtenir des informations personnalisées directement à partir de votre environnement et de consulter les conversations précédentes.

Vous pouvez ouvrir Ask Me depuis n'importe quelle page en cliquant sur le nouveau signet. Cela lance Ask Me dans un panneau latéral sans interrompre votre travail en cours et propose des explications et des recommandations rapides en rapport avec ce que vous faites.

link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html#features["En savoir plus sur Ask Me"]



=== Charges de travail EDA



==== Tableau de bord de synthèse pour la gestion du stockage EDA

En tant qu'administrateur informatique gérant des dizaines de systèmes de fichiers FSx for ONTAP, vous pouvez utiliser le tableau de bord de synthèse pour répondre aux questions opérationnelles courantes concernant l'état du cluster, son utilisation et l'emplacement des volumes.

Le tableau de bord de synthèse comprend :

* *État de santé du cluster* : Informations résumées en haut du tableau de bord qui mettent en évidence les performances, la capacité, la disponibilité, la protection et les événements de sécurité de vos clusters.
* *Tableau des clusters* : un tableau consultable, filtrable et paginé affichant la capacité SSD, le pool de capacité et les métriques de débit par cluster, avec prise en charge de la personnalisation des colonnes et de l’exportation CSV.


L'ancien tableau de bord principal est désormais accessible dans l'onglet *Projet*. Les onglets EDA sont maintenant ordonnés : Vue d'ensemble, Latence, Projet, CI/CD.

https://docs.netapp.com/us-en/workload-eda/task-use-overview-dashboard.html["En savoir plus sur le tableau de bord de présentation"^].



==== Analyse automatisée de la latence

L'analyse de latence inclut désormais une analyse de base automatisée. Lorsque des événements de latence sont détectés, le système analyse automatiquement les métriques du centre de délai QoS ONTAP afin d'identifier la source des problèmes de latence.

L'analyse de base évalue les politiques QoS, les performances du disque, les problèmes de réseau et les configurations du cluster afin de fournir des informations immédiates dans la colonne Details du tableau des événements de latence.

https://docs.netapp.com/us-en/workload-eda/task-monitor-latency.html#understanding-basic-analysis["En savoir plus sur l'analyse de latence de base"^].



==== Nouveau signet Ask Me disponible dans Workload Factory

Nous avons ajouté un nouveau raccourci Ask Me sur chaque écran de la console Workload Factory. Cette amélioration vous permet d'accéder plus facilement et plus rapidement à Ask Me chaque fois que vous avez besoin d'aide. Ask Me est notre assistant IA, qui vous permet de poser des questions sur vos propres environnements de charge de travail, d'obtenir des informations personnalisées directement à partir de votre environnement et de consulter les conversations précédentes.

Vous pouvez ouvrir Ask Me depuis n'importe quelle page en cliquant sur le nouveau signet. Cela lance Ask Me dans un panneau latéral sans interrompre votre travail en cours et offre des explications et des recommandations rapides en rapport avec ce que vous faites actuellement.

link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html#features["En savoir plus sur Ask Me"^]



== 16 février 2026



=== Amazon FSX pour NetApp ONTAP



==== Prise en charge de la migration des VM de stockage

NetApp Workload Factory prend désormais en charge la migration des machines virtuelles de stockage. Cette fonctionnalité permet la migration des données et des configurations des systèmes de stockage ONTAP depuis des systèmes ONTAP sur site ou des systèmes de fichiers FSx for ONTAP de première génération vers des systèmes de fichiers FSx for ONTAP de deuxième génération. Vous pouvez répliquer les données et les paramètres de configuration des machines virtuelles de stockage vers le nouveau système de fichiers avec une interruption minimale et une perturbation réduite pour les utilisateurs et les applications.

Pour utiliser cette fonctionnalité, link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["créer une relation de réplication"] et sélectionnez *Migration* comme cas d'utilisation. Pour mener à bien le processus de migration, vous devez link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html#cut-over-replication-for-migration-use-cases["basculer la machine virtuelle de stockage et ses volumes répliqués"] immédiatement pour migrer définitivement les données et les paramètres de configuration de la machine virtuelle de stockage vers le système de fichiers FSx for ONTAP cible.



== 02 février 2026



=== Charges de travail des bases de données



==== Économies améliorées pour plusieurs hôtes de base de données sur Microsoft SQL Server en local

L'analyse des économies pour le stockage sur site de Microsoft SQL Server a été améliorée afin de fournir une solution de stockage consolidée pour plusieurs hôtes de base de données sur un seul système de fichiers FSx for ONTAP. Cette consolidation optimise les coûts de stockage en réduisant le nombre de systèmes de fichiers nécessaires pour plusieurs hôtes de base de données, ce qui permet d'améliorer les économies.

link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html#explore-savings-for-detected-hosts["Explorez les économies pour les hôtes détectés sur Microsoft SQL Server sur site"]



==== Analyse bien architecturée pour Oracle

L'analyse bien architecturée comprend quatre nouvelles sous-évaluations pour l'analyse de la configuration de stockage pour Oracle : activation de dNFS, résolution IP cohérente de dNFS, fichier de configuration dNFS, et dNFS `nosharecache`. Ces évaluations concernent l'activation et la configuration de Direct NFS (dNFS) pour votre environnement Oracle, qui contourne le client NFS hôte et effectue les opérations de fichiers NFS directement sur un serveur NFS, améliorant les performances d'E/S et diminuant la charge sur l'hôte et le système de stockage car les E/S sont effectuées de manière plus efficace.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implémenter des configurations de base de données bien architecturées dans Workload Factory"]



== 01 février 2026



=== Amazon FSX pour NetApp ONTAP



==== La page d'accueil inclut des problèmes bien architecturés et des événements EMS pour le stockage

La page d'accueil de NetApp Workload Factory comprend une vignette Focus où les problèmes bien architecturés et les événements Emergency Management System (EMS) FSx for ONTAP apparaissent pour vos charges de travail. À partir de là, vous pouvez accéder à la charge de travail Stockage pour consulter le statut bien architecturé ou les événements de tous les systèmes de fichiers FSx for ONTAP dans votre environnement de stockage.



==== Prise en charge de la réplication des données à l'aide d'un point d'accès S3

Workload Factory prend en charge la réplication des données ONTAP locales vers le cloud pour l'intégration avec AWS GenAI, le ML et l'analytique. Vous pouvez répliquer vos données locales sur un volume NFS ou SMB/CIFS à l'aide d'un point d'accès S3.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Répliquez les données sur site à l'aide d'un point d'accès S3"]



==== Améliorations du point d'accès S3 dans le stockage

Plusieurs améliorations ont été apportées aux capacités de gestion des points d'accès S3 dans la charge de travail Stockage pour NetApp Workload Factory. Vous pouvez saisir les détails de configuration réseau pour vos points d'accès S3 et ajouter des balises de points d'accès S3. Des améliorations supplémentaires incluent la possibilité de consulter les détails des compartiments S3 et d'effectuer davantage d'actions pour gérer les points d'accès S3.



===== Détails du bucket S3 disponibles dans Storage

La nouvelle table d'inventaire analyse automatiquement vos compartiments AWS S3 et alimente les tables S3 pour vous offrir un aperçu clair de tous les objets, de leurs métadonnées, attributs et balises. L'accès à ces informations vous permet de garder le contrôle, la visibilité et la confiance dans les données dont vous êtes responsable, tout en réduisant la charge opérationnelle. Vous pouvez activer cette fonctionnalité lors de la création et de l'association de points d'accès S3 ou lors de la modification de points d'accès existants.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-s3-access-point.html["Créez et associez un point d'accès à un volume dans NetApp Workload Factory"]



===== Opérations de gestion supplémentaires pour les points d'accès S3

NetApp Workload Factory offre des opérations de gestion supplémentaires pour les points d'accès S3. Vous pouvez consulter les détails des points d'accès, modifier les points d'accès S3 existants, et ajouter ou supprimer des balises de points d'accès S3 depuis l'interface NetApp Workload Factory, ce qui simplifie vos tâches de gestion du stockage objet.



==== Mises à jour d'analyse bien conçues

Workload Factory analyse vos systèmes de fichiers FSx pour ONTAP pour les configurations suivantes :

* Optimiser la taille du volume de cache : vérifie si le dimensionnement automatique et le nettoyage sont activés sur les volumes de cache afin de maintenir une taille optimale et de concentrer le cache sur les données chaudes pour une efficacité maximale.
* Périphériques de stockage inactifs : recommande d’archiver les données du périphérique de stockage ou de supprimer un périphérique de stockage s’il n’a pas été utilisé pendant sept jours consécutifs.
* Rapports logiques de la VM de stockage : vérifie si le paramètre de rapport par défaut d’une VM de stockage est défini sur logique, ce qui offre une meilleure visibilité sur l’utilisation du stockage au niveau du volume.




==== Cartes supplémentaires pour les périphériques de stockage bloc

Trois nouvelles cartes ont été ajoutées à l'onglet Block devices dans la charge de travail Stockage afin de fournir un aperçu rapide de l'utilisation et de l'état de protection des block devices :

* Efficacités du stockage : affiche la capacité de stockage utilisée et disponible ; la capacité utilisée est ventilée par niveaux de stockage SSD et pool de capacité.
* Appareils protégés : affiche le pourcentage d’appareils de stockage bloc disposant d’instantanés, de réplication à distance, de protection autonome contre les ransomwares (ARP/AI) NetApp et de sauvegardes.
* Périphériques de stockage inactifs : ce message indique si des périphériques de stockage n’ont pas été utilisés pendant sept jours consécutifs, ce qui vous permet d’identifier et de gérer efficacement les ressources inutilisées. À partir de là, vous pouvez link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-storage.html#archive-the-data-of-an-inactive-block-device["récupérer de l'espace pour les périphériques bloc inutilisés"].




==== Prise en charge de la création et de la gestion de groupes d'initiateurs

NetApp Workload Factory prend en charge la création et la gestion de groupes d'initiateurs (igroups) pour le stockage bloc dans les systèmes de fichiers FSx for ONTAP. Les groupes d'initiateurs connectent les périphériques de stockage bloc (LUN) aux ressources de calcul autorisées à y accéder, fournissant une couche d'autorisation pour le stockage bloc dans les environnements SAN.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-igroup.html["Créez un groupe d'initiateurs dans NetApp Workload Factory"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-igroups.html["Gérer les groupes d'initiateurs existants dans NetApp Workload Factory"]




=== Workloads VMware



==== Analyse bien architecturée pour Amazon Elastic VMware Service

Workload Factory propose désormais une analyse automatisée bien architecturée de vos environnements Amazon Elastic VMware Service (EVS). Des analyses quotidiennes identifient les incohérences de configuration et offrent des recommandations de remédiation détaillées pour vous aider à maintenir des opérations, une sécurité et une efficacité des coûts optimales.

Les analyses sont effectuées à l'aide des API AWS—aucun identifiant vSphere ni connexion vCenter n'est requis. Les résultats sont disponibles dans le nouvel onglet *Well-architected status* des détails de votre environnement EVS.

Cette version inclut des informations sur :

* *État de la protection contre l'arrêt/la suppression des instances* : Identifie les nœuds EVS sans protection contre l'arrêt ou la suppression EC2. L'arrêt ou la suppression de nœuds EVS depuis la console EC2 peut entraîner l'indisponibilité des données de la machine virtuelle ou une perte de données.
* *Alignement du placement des partitions des nœuds du cluster* : détecte les désalignements de partitionnement susceptibles d’entraîner une perte de puissance de traitement importante ou une interruption en cas de défaillance d’une partition au sein d’une AWS Availability Zone. Chaque insight comprend des niveaux de gravité, des résultats détaillés avec des informations sur les ressources impactées et des procédures de correction étape par étape basées sur les bonnes pratiques AWS.


link:view-evs-well-architected.html["Mettre en œuvre des configurations bien architecturées"]



=== Configuration et administration



==== Mises à jour bien conçues

NetApp Workload Factory inclut l'évaluation bien architecturée pour les charges de travail Elastic VMware Service (EVS) et ajoute de nouvelles configurations pour les charges de travail de stockage et de base de données.

* *Charges de travail VMware* NetApp Workload Factory fournit des bonnes pratiques et des recommandations pour l'exploitation de charges de travail Amazon Elastic VMware Service (EVS) bien architecturées.
+
link:https://docs.netapp.com/us-en/workload-vmware/view-evs-well-architected.html["Mettre en œuvre des configurations EVS bien architecturées"^]

* *Charges de travail de stockage* Plusieurs nouvelles configurations ont été ajoutées à la fonctionnalité bien conçue dans la charge de travail de stockage afin que vous ayez plus d'informations sur les performances et les coûts de stockage.
+
** Rapports logiques des Storage VM
** Optimiser la taille du volume de cache
** Périphériques de bloc orphelins
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Mettre en œuvre des configurations de système de fichiers bien architecturées pour les charges de travail Storage"^]



* *Charges de travail de base de données* Workload Factory for Databases inclut une nouvelle configuration de stockage pour Oracle permettant d'activer et de configurer Direct NFS (dNFS) afin d'améliorer les performances d'E/S et de réduire la charge sur l'hôte et le système de stockage.
+
** Activation de dNFS
** résolution IP cohérente dNFS
** fichier de configuration dNFS
** dNFS `nosharecache`
+
link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Mettre en œuvre des charges de travail de base de données bien architecturées"^]







==== Nouvelles autorisations pour Storage

De nouvelles autorisations ont été ajoutées à la charge de travail Storage pour des améliorations de la gestion des points d'accès S3.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Journal des modifications de référence des autorisations"]



=== Charges de travail EDA



==== Filtrage amélioré du tableau de bord avec des balises personnalisables

Vous pouvez désormais configurer jusqu'à cinq filtres personnalisés sur le tableau de bord EDA en fonction de vos balises AWS. Chaque filtre personnalisé comprend un nom de label, une clé de balise AWS et un type de sélection (sélection unique ou multiple).

La sélection multiple vous permet de sélectionner plusieurs valeurs simultanément, tandis que la sélection unique vous limite à une valeur à la fois. Les filtres personnalisés apparaissent dans l'ordre dans lequel vous les configurez, ce qui facilite l'organisation de vos filtres les plus fréquemment utilisés.

Si vous ne configurez pas de filtres personnalisés, les filtres par défaut (système de fichiers, type de volume et plage horaire) restent disponibles afin que vous puissiez continuer à consulter et à interagir avec vos tableaux de bord.

https://docs.netapp.com/us-en/workload-eda/task-configure-dashboard.html["En savoir plus sur la configuration des filtres personnalisés"^].



==== Vue des détails du volume pour une analyse granulaire des performances

Le tableau de bord propose désormais deux modes d'affichage : Total view et Volume view. Le mode Total view affiche des indicateurs agrégés pour l'ensemble des volumes, tandis que le mode Volume view présente les performances individuelles des 10 principaux volumes au fil du temps.

En mode Volume, des infobulles interactives s'affichent au survol de la souris et fournissent des informations détaillées pour chaque volume, y compris le nom du volume, les métriques et les valeurs spécifiques à un moment donné. Lorsque les mêmes volumes apparaissent dans plusieurs composants, un code couleur cohérent facilite le suivi de volumes spécifiques à travers différentes métriques.

https://docs.netapp.com/us-en/workload-eda/task-configure-dashboard.html#view-volume-details["En savoir plus sur l'affichage des détails du volume"^].



==== Analyse de la latence pour la surveillance proactive des performances

L'analyse de latence vous permet de surveiller la latence de lecture et d'écriture des volumes sur vos systèmes de fichiers FSx for ONTAP. Vous pouvez configurer des seuils d'alerte et d'événements critiques personnalisables afin d'identifier proactivement les goulots d'étranglement des performances avant qu'ils n'affectent vos charges de travail EDA.

Le tableau des événements de latence affiche tous les événements d'avertissement et critiques, vous permettant de surveiller les performances des volumes et d'identifier les volumes qui nécessitent une optimisation.

Cette fonctionnalité nécessite des identifiants AWS et est accessible depuis le menu Latency du tableau de bord EDA.

https://docs.netapp.com/us-en/workload-eda/task-monitor-latency.html["En savoir plus sur l'analyse de latence"^].
