---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: 'Découvrez les derniers changements apportés aux charges de travail de l"usine BlueXP .' 
---
= Modifications récentes de l'usine de workloads BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Découvrez les derniers changements apportés aux charges de travail de l'usine BlueXP .



== 2025-05-04



=== Amazon FSX pour NetApp ONTAP



==== Protection anti-ransomware autonome pour les systèmes de fichiers FSX pour ONTAP

Protégez vos données avec la protection anti-ransomware autonome (ARP), une fonctionnalité qui utilise l'analyse des workloads dans les environnements NAS (NFS/SMB) pour détecter et signaler les activités anormales qui pourraient être une attaque par ransomware. Lorsqu'une attaque est suspectée, ARP crée également de nouveaux snapshots immuables à partir desquels vous pouvez restaurer vos données.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["Protégez vos données avec la protection anti-ransomware autonome"]



==== Amélioration du rééquilibrage des volumes FlexGroup

BlueXP  Workload Factory lance l'assistant de rééquilibrage des volumes FlexGroup avec plusieurs options de disposition pour le rééquilibrage des données dans un volume FlexGroup. Le rééquilibrage redistribue les données de façon homogène vers les volumes de membres FlexGroup.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/rebalance-volume.html["Rééquilibrez la capacité d'un volume FlexGroup"]



==== Implémentez les bonnes pratiques pour un système de fichiers FSX pour ONTAP

La fabrique de charges de travail BlueXP  fournit un tableau de bord dans lequel vous pouvez consulter l'état de l'architecture de vos configurations de système de fichiers. Cette analyse vous permet d'implémenter les bonnes pratiques pour vos systèmes de fichiers FSX pour ONTAP. L'analyse de la configuration du système de fichiers comprend les configurations suivantes : seuil de capacité SSD, snapshots locaux programmés, sauvegardes FSX pour ONTAP, Tiering des données et réplication des données à distance.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html["En savoir plus sur l'analyse bien conçue pour les configurations de système de fichiers"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Implémentez les meilleures pratiques pour vos systèmes de fichiers"]




==== Options de type de sécurité des volumes à double protocole

Vous avez la possibilité de choisir NTFS ou UNIX comme style de sécurité pour un volume afin de déterminer la méthode d'accès des utilisateurs et des autorisations à un volume.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Créer un volume"]



==== Amélioration de la réplication



===== Réplication inverse prise en charge à partir de FSX pour ONTAP vers l'environnement sur site

La réplication inverse est désormais disponible depuis un système de fichiers FSX pour ONTAP vers un cluster ONTAP sur site depuis la console d'usine des workloads.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/reverse-replication.html["Réplication inverse"]



===== Réplication de volume de protection des données

Il est désormais possible de répliquer des volumes de protection des données.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/cascade-replication.html["Réplication d'un volume de protection des données"]



===== Sélection de plusieurs volumes

La sélection de plusieurs volumes est disponible pour vous permettre de sélectionner exactement les volumes à répliquer.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Créer une relation de réplication"]



===== Étiquettes de politique de conservation à long terme

Lorsque vous activez la conservation à long terme pour une relation de réplication, les étiquettes des volumes source et cible doivent correspondre exactement. Désormais, l'usine de workloads BlueXP  peut automatiquement créer des étiquettes de volume source manquantes pour vous.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Créer une relation de réplication"]



==== Nom de fichier FSX pour ONTAP visible lors de la création du volume

Nous avons amélioré la visibilité des systèmes de fichiers FSX pour ONTAP lors de la création des volumes. Lorsque vous créez un volume, le système de fichiers FSX pour ONTAP s'affiche. Vous savez ainsi exactement où le volume est créé.



==== Compte AWS visible dans l'ensemble de la charge de travail stockage

Nous avons amélioré la visibilité des comptes sur la charge de travail de stockage. Le compte AWS s'affiche lorsque vous accédez aux onglets *volumes*, *Storage VM* et *Replication*.



==== Améliorations de l'association de liens

* Vous pouvez rapidement associer un lien à partir d'un système de fichiers FSX pour ONTAP dans l'onglet Inventaire.
* La fabrique de charges de travail BlueXP  prend désormais en charge l'utilisation d'autres informations d'identification utilisateur ONTAP pour l'association de liaisons.




==== Prise en charge de l'authentification de liens pour AWS secrets Manager

Vous avez désormais la possibilité d'utiliser les secrets d'AWS secrets Manager pour authentifier les liens afin de ne pas avoir à utiliser les informations d'identification stockées dans l'usine de workloads BlueXP .



==== Assistance de suivi

Tracker fournit désormais des réponses API pour que vous puissiez voir la sortie de l'API REST associée à la tâche.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/monitor-operations.html["Surveiller les opérations avec Tracker"]



==== Validation de la capacité lors de la restauration d'un volume à partir d'une sauvegarde

Lors de la restauration d'un volume à partir d'une sauvegarde, l'usine de workloads BlueXP  détermine si vous disposez de suffisamment de capacité pour la restauration et peut ajouter automatiquement de la capacité de Tier de stockage SSD si ce n'est pas le cas.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/restore-from-backup.html["Restaurer un volume à partir d'une sauvegarde"]



==== Prise en charge d'autres informations d'identification utilisateur ONTAP

L'usine de workloads prend désormais en charge d'autres ensembles d'identifiants ONTAP pour la création de systèmes de fichiers afin de minimiser les risques liés à la sécurité. Au lieu d'utiliser uniquement l'utilisateur fsxadmin, vous pouvez sélectionner un autre ensemble d'informations d'identification ONTAP ou choisir de ne pas fournir de mot de passe aux utilisateurs fsxadmin et vsaadmin.



==== Mise à jour de la terminologie des autorisations

L'interface utilisateur et la documentation de l'usine de la charge de travail utilisent désormais « lecture seule » pour faire référence aux autorisations de lecture et « lecture-écriture » pour faire référence aux autorisations d'automatisation.



=== Charges de travail des bases de données



==== Améliorations du tableau de bord

* Des vues multi-comptes et inter-régions sont disponibles lorsque vous naviguez entre les onglets dans la console BlueXP  Workload Factory. Ces nouvelles vues améliorent la gestion, la surveillance et l'optimisation des ressources.
* À partir de la mosaïque *économies potentielles* du tableau de bord, vous pourrez rapidement consulter les économies que vous pourriez réaliser en passant à FSX pour ONTAP à partir d'Amazon Elastic Block Store ou d'Amazon FSX pour serveur de fichiers Windows.




==== Analyse ad hoc disponible pour les configurations de base de données

L'usine de workloads BlueXP  pour les bases de données analyse automatiquement les instances Microsoft SQL Server gérées avec FSX pour le stockage ONTAP en vue d'identifier les problèmes de configuration potentiels. Désormais, en plus de l'acquisition quotidienne, vous pouvez numériser à tout moment.



==== Suppression des dossiers d'évaluation sur place

Après avoir étudié les économies réalisées pour un hôte sur site Microsoft SQL Server, vous avez la possibilité de supprimer l'enregistrement hôte sur site de l'usine de charge de travail BlueXP .



==== Optimisation améliorée



===== Nettoyage des clones

L'évaluation et la correction du nettoyage des clones permettent d'identifier et de gérer les clones anciens et coûteux. Les clones de plus de 60 jours peuvent être actualisés ou supprimés de la console d'usine de la charge de travail BlueXP .



===== Reporter et ignorer l'analyse de la configuration

Certaines configurations peuvent ne pas s'appliquer à vos environnements de base de données. Vous pouvez à présent différer de 30 jours l'analyse d'une configuration donnée ou rejeter l'analyse.



==== Suppression des dossiers d'évaluation sur place

Après avoir étudié les économies réalisées pour un hôte sur site Microsoft SQL Server, vous avez la possibilité de supprimer l'enregistrement hôte sur site de l'usine de charge de travail BlueXP .



==== Mise à jour de la terminologie des autorisations

L'interface utilisateur et la documentation de l'usine de la charge de travail utilisent désormais « lecture seule » pour faire référence aux autorisations de lecture et « lecture-écriture » pour faire référence aux autorisations d'automatisation.



=== Workloads VMware



==== Améliorations d'Amazon EC2 migration Advisor

Cette version de la fabrique de workloads BlueXP  pour VMware offre les améliorations suivantes à l'expérience de migration Advisor dans Amazon EC2 :

*Informations sur l'infrastructure de données NetApp en tant que source de données* : la fabrique de workloads se connecte désormais directement aux informations sur l'infrastructure de données NetApp pour collecter des informations sur le déploiement VMware lorsque vous utilisez le collecteur de données EC2 migration Advisor.

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Créez un plan de déploiement pour Amazon EC2 à l'aide du conseiller de migration"]



==== Mise à jour de la terminologie des autorisations

L'interface utilisateur et la documentation de l'usine de la charge de travail utilisent désormais « lecture seule » pour faire référence aux autorisations de lecture et « lecture-écriture » pour faire référence aux autorisations d'automatisation.



=== Charges de travail GenAI



==== Prise en charge de NetApp ONTAP Connector pour Amazon Q

Cette version de GenAI introduit la prise en charge de NetApp ONTAP Connector pour Amazon Q, qui vous permet de créer des connecteurs pour Amazon Q Business. Profitez rapidement et facilement de l'assistant IA Amazon Q Business avec moins de configuration initiale qu'en construisant une base de connaissances GenAI pour le socle Amazon.

link:https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html["Créez un connecteur GenAI pour Amazon Q Business"]



==== Prise en charge améliorée des modèles de chat

GenAI prend désormais en charge les modèles de chat supplémentaires suivants pour les bases de connaissances :

* link:https://docs.mistral.ai/getting-started/models/models_overview/["Modèles d'IA Mistral"^]
* link:https://docs.aws.amazon.com/bedrock/latest/userguide/titan-text-models.html["Modèles texte Amazon Titan"^]
* link:https://www.llama.com/docs/model-cards-and-prompt-formats/["Modèles META Llama"^]
* link:https://docs.ai21.com/["Modèles Jamba 1.5"^]
* link:https://docs.cohere.com/docs/the-cohere-platform["Modèles Cohere Command"^]
* link:https://aws.amazon.com/bedrock/deepseek/["Modèles DeepSeek"^]


GenAI prend en charge les modèles de chaque fournisseur pris en charge par Amazon Bedrock : link:https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html["Modèles de base pris en charge dans Amazon Bedrock"^]

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html["Créer une base de connaissances GenAI"]



==== Mise à jour de la terminologie des autorisations

L'interface utilisateur et la documentation de l'usine de la charge de travail utilisent désormais « lecture seule » pour faire référence aux autorisations de lecture et « lecture-écriture » pour faire référence aux autorisations d'automatisation.



=== Configuration et administration



==== Prise en charge de CloudShell avec remplissage automatique

Lorsque vous utilisez BlueXP  Workload Factory CloudShell, vous pouvez commencer à taper une commande et appuyer sur la touche Tab pour afficher les options disponibles. S'il existe plusieurs possibilités, l'interface de ligne de commande affiche une liste de suggestions. Cette fonction améliore la productivité en réduisant au minimum les erreurs et en accélérant l'exécution des commandes.



==== Mise à jour de la terminologie des autorisations

L'interface utilisateur et la documentation de l'usine de la charge de travail utilisent désormais « lecture seule » pour faire référence aux autorisations de lecture et « lecture-écriture » pour faire référence aux autorisations d'automatisation.



== 2025-04-04



=== Charges de travail des bases de données



==== Optimisation améliorée

Lors de l'optimisation de vos environnements de base de données, de nouvelles évaluations d'optimisation, des corrections et l'affichage de plusieurs ressources sont disponibles.



===== Évaluations de résilience

Ces améliorations incluent de nouvelles évaluations de la résilience pour vérifier que les fonctionnalités de redondance des données et de reprise d'activité sont configurées pour vos environnements de base de données.

* Sauvegardes FSX pour ONTAP : analyse si les systèmes de fichiers FSX pour ONTAP qui desservent les volumes de l'instance SQL Server sont configurés avec des sauvegardes FSX pour ONTAP planifiées.
* Réplication interrégionale : vérifie si les systèmes de fichiers FSX pour ONTAP qui servent des instances de Microsoft SQL Server sont configurés avec la réplication interrégionale.




===== Résolution des problèmes de calcul

La correction RSS (Receive Side Scaling) configure RSS pour distribuer le traitement réseau sur plusieurs processeurs et assurer une distribution de charge efficace.



===== Correction locale des snapshots

La correction locale des snapshots définit des règles de snapshot pour les volumes de vos instances Microsoft SQL Server afin de préserver la résilience de vos environnements de base de données en cas de perte de données.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Optimiser les configurations"]



===== Prise en charge de la sélection de plusieurs ressources

Lors de l'optimisation des configurations de base de données, vous pouvez désormais sélectionner des ressources spécifiques au lieu de toutes les ressources.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Optimiser les configurations"]



==== Vue Inventaire améliorée

L'onglet Inventaire de la console d'usine des workloads a été rationalisé de sorte qu'il ne contienne que les serveurs SQL s'exécutant sur Amazon FSX pour NetApp ONTAP. Vous trouverez maintenant des serveurs SQL sur site et s'exécutant sur Amazon Elastic Block Store et Amazon FSX pour Windows File Server dans l'onglet économies Explore.



==== Création rapide disponible pour le déploiement du serveur PostgreSQL

Vous pouvez utiliser cette option de déploiement rapide pour créer un serveur PostgreSQL avec une configuration haute disponibilité et les meilleures pratiques intégrées.

link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["Créez un serveur PostgreSQL en usine de charges de travail BlueXP"]



== 2025-03-30



=== Amazon FSX pour NetApp ONTAP



==== Gestion automatique de la capacité pour les systèmes scale-out

L'usine de charges de travail recherche désormais les inodes disponibles dans les volumes et augmente leur nombre en fonction des seuils configurés de gestion automatique de la capacité. Cette fonctionnalité prend en charge la gestion automatique de la capacité pour les systèmes scale-out. Vous pouvez activer la gestion des inodes dans le cadre de la gestion automatique de la capacité.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html["Activez la gestion automatique de la capacité"]



==== API de rééquilibrage FlexGroup

L'usine de charges de travail BlueXP  lance l'API de rééquilibrage FlexGroup qui vous permet d'exécuter un plan de rééquilibrage des données dans une FlexGroup. Le rééquilibrage redistribue les données uniformément aux volumes membres.

link:https://console.workloads.netapp.com/api-doc["Documentation de l'API BlueXP  Workload Factory"]



==== Le formulaire de réplication de données inclut des cas d'utilisation

Le formulaire de données répliquées comprend désormais des cas d'utilisation qui vous permettent de remplir plus facilement le formulaire. Sélectionnez l'un des cas d'utilisation suivants pour la réplication des données : migration, reprise après incident à chaud, reprise après incident à froid, archivage ou autre. Après avoir sélectionné un cas d'utilisation, Workload Factory recommande des valeurs conformément aux meilleures pratiques. Vous pouvez accepter les valeurs présélectionnées ou les personnaliser dans le formulaire.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Réplication des données"]



==== Modifications de la terminologie des règles de Tiering des données

Lorsque vous sélectionnez une règle de Tiering lors de la création de volumes, de la réplication de données ou des mises à jour de règles de Tiering existantes, vous trouverez de nouveaux termes qui décrivent les règles de Tiering.

* _Équilibré (auto)_
* _Optimisation des coûts (tous)_
* _Optimisation des performances (snapshots uniquement)_




==== Détails du groupe de sécurité pour la création du système de fichiers

Un groupe de sécurité est créé dans le cadre du processus de création du système de fichiers FSX pour ONTAP. Les détails des groupes de sécurité, notamment les protocoles, les ports et les rôles, sont désormais disponibles.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Créez un système de fichiers"]



=== Workloads VMware



==== Améliorations d'Amazon EC2 migration Advisor

Cette version de la fabrique de workloads BlueXP  pour VMware apporte plusieurs améliorations à l'expérience de l'outil de conseil en migration Amazon EC2 :

* *Conseils améliorés d'attribution de volume* : les informations d'affectation de volume des étapes « classifier » et « Package » du conseiller de migration EC2 offrent une meilleure lisibilité et une plus grande facilité d'utilisation. Des informations plus utiles s'affichent sur chaque volume pour vous permettre de mieux identifier les volumes et de déterminer comment les attribuer.
* *Améliorations de l'efficacité du script du collecteur de données* : le script du collecteur de données EC2 migration Advisor optimise l'utilisation du processeur lors de la collecte de données pour les déploiements de machines virtuelles plus petits.


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Créez un plan de déploiement pour Amazon EC2 à l'aide du conseiller de migration"]



=== Charges de travail GenAI



==== Prise en charge améliorée des types de fichiers

Cette version de GenAI introduit la prise en charge des formats de fichiers JSON et JSONP lors de l'ingénification `.json` des fichiers à partir de sources de données. Les fichiers JSON avec des objets imbriqués sont pris en charge, avec une prise en charge limitée des tableaux imbriqués.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/identify-data-sources-knowledge-base.html#supported-data-source-file-formats["Formats de fichiers de source de données pris en charge"]



==== Prise en charge de l'internationalisation de l'exemple d'application de chatbot externe

Vous pouvez désormais facilement modifier l'interface utilisateur de l'exemple d'application de chatbot externe GenAI en une langue ou un environnement local différent.

link:https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/AI/GenAI-ChatBot-application-sample#netapp-workload-factory-genai-sample-application["Exemple d'application externe de chatbot GenAI"]



==== Support pour le modèle de chat Anthropique Claude Sonnet 3.7

GenAI inclut maintenant le support pour le modèle de chat Anthropique Claude 3.7 Sonnet. Les fonctionnalités bêta de Claude 3.7 Sonnet permettent jusqu'à 128 K jetons de sortie par demande et prennent en charge de nouvelles actions d'utilisation d'ordinateur. Claude 3.7 le mode de pensée étendue Sonnet sera pris en charge dans une future version de GenAI.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["Créer une base de connaissances GenAI"]



==== Prise en charge de l'ajout de sources de données à partir de partages NFS/SMB génériques

En utilisant l'API des fabrique de workloads, vous pouvez désormais ajouter une source de données à partir d'un partage NFSv3, NFSv4 ou SMB générique. Lorsque vous ajoutez une source de données à partir d'un partage NFS ou SMB, le volume de la base de connaissances reste sur un volume Amazon FSX pour NetApp ONTAP. L'interface utilisateur Web d'usine de la charge de travail prendra en charge cette fonctionnalité dans une prochaine version.

link:https://console.workloads.netapp.com/api-doc["Utilisez l'API d'usine des workloads"^]



==== Prise en charge du peering VPC

Vous pouvez désormais déployer une infrastructure GenAI dans la link:https://docs.aws.amazon.com/vpc/latest/peering/what-is-vpc-peering.html["Clouds privés virtuels peering (VPC)"^]même région et utiliser le même compte AWS. Vous pouvez déployer le moteur d'IA dans un VPC, puis créer une base de connaissances dans un VPC à peering, et sélectionner les systèmes de fichiers Amazon FSX pour NetApp ONTAP qui résident dans un VPC à peering.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["Créer une base de connaissances GenAI"]



=== Configuration et administration



==== CloudShell signale les réponses d'erreur générées par l'IA pour les commandes de l'interface de ligne de commande ONTAP

Lorsque vous utilisez CloudShell, chaque fois que vous exécutez une commande de l'interface de ligne de commande ONTAP et qu'une erreur se produit, vous pouvez obtenir des réponses d'erreur générées par l'IA incluant une description de l'échec, la cause de l'échec et une résolution détaillée.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Utilisez CloudShell"]



==== iam:mise à jour des autorisations SimulatePermissionPolicy

Vous pouvez désormais gérer les `iam:SimulatePrincipalPolicy` autorisations à partir de la console d'usine des charges de travail lorsque vous ajoutez des informations d'identification de compte AWS supplémentaires ou que vous ajoutez une nouvelle fonctionnalité de charge de travail telle que la charge de travail GenAI.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Journal des modifications de référence des autorisations"]



== 2025-03-03



=== Charges de travail des bases de données



==== Configuration PostgreSQL haute disponibilité

Vous pouvez maintenant déployer une configuration haute disponibilité pour le serveur PostgreSQL.

link:https://review.docs.netapp.com/us-en/workload-databases_explore-savings-updates/create-postgresql-server.html["Créez un serveur PostgreSQL"]



==== Prise en charge de Terraform pour la création de serveur PostgreSQL

Vous pouvez maintenant utiliser Terraform à partir de Codebox pour déployer PostgreSQL.

* link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["Créez un serveur de base de données PostgreSQL"]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["Utiliser Terraform à partir de Codebox"]




==== Évaluation de la résilience pour la planification des snapshots locaux

Une nouvelle évaluation de la résilience est disponible pour les charges de travail de la base de données. Nous évaluons si les volumes de vos instances Microsoft SQL Server disposent de règles de snapshot planifiées valides. Les copies Snapshot sont des copies instantanées de vos données et contribuent à la résilience de vos environnements de base de données en cas de perte de données.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Optimiser les configurations"]



==== Correction MAXDOP pour les charges de travail de base de données

L'usine de charges de travail BlueXP  pour les bases de données prend désormais en charge la correction pour la configuration maximale du serveur de degré de parallélisme (MAXDOP). Lorsque la configuration MAXDOP n'est pas optimale, vous pouvez laisser BlueXP  charge de travail usine optimiser la configuration pour vous.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Optimiser les configurations"]



==== Rapport d'analyse des économies par e-mail

Lorsque vous découvrez les économies pour vos environnements de stockage Amazon Elastic Block Store et FSX pour serveur de fichiers Windows par rapport à FSX pour ONTAP, vous pouvez désormais envoyer le rapport de recommandations par e-mail à vous-même, aux membres de l'équipe et aux clients.



== 2025-03-02



=== Amazon FSX pour NetApp ONTAP



==== Amélioration de la gestion automatique de la capacité

Lorsque la gestion automatique de la capacité est activée, l'usine de workloads BlueXP  vérifie à présent si un système de fichiers a atteint son seuil de capacité toutes les 30 minutes au lieu de toutes les 2 heures.

Le paramètre IOPS provisionnées n'est plus affecté lorsque le seuil de capacité est atteint.



==== Snapshots immuables

Vous pouvez désormais verrouiller les snapshots, les rendant immuables, pour une période de conservation spécifique. Le verrouillage empêche les accès non autorisés et les suppressions malveillantes des snapshots. Vous pouvez activer des snapshots immuables lors de la création de règles relatives aux snapshots, lors de la création manuelle de snapshots et après la création de snapshots.



==== Mise à jour des fichiers immuables

Vous pouvez maintenant apporter les modifications suivantes à votre configuration de fichiers immuables : règle de conservation, période de conservation, période de validation automatique et mode d'ajout des volumes.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-immutable-files.html["Gérer les fichiers immuables"]



==== Amélioration de la réplication des données

* Réplication entre comptes : la réplication entre deux comptes AWS est prise en charge dans la console d'usine des workloads BlueXP  ainsi que la gestion de la réplication.
* Mettre en pause et reprendre la réplication : vous pouvez interrompre (arrêter) les mises à jour de réplication planifiées du volume source vers le volume de destination, puis reprendre la planification de réplication lorsque vous êtes prêt. Pendant la pause, les volumes source et de destination deviennent indépendants et le volume de destination passe de la lecture seule à la lecture-écriture.
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/pause-resume-replication.html["Mettre en pause et reprendre une relation de réplication"]





==== Événements CloudShell dans Tracker

Vous pouvez désormais suivre les événements CloudShell dans Tracker.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/monitor-operations.html["Apprenez à surveiller et suivre les opérations avec Tracker"]



=== Workloads VMware



==== Améliorations d'Amazon EC2 migration Advisor

Cette version de la fabrique de workloads BlueXP  pour VMware apporte plusieurs améliorations à l'expérience de l'outil de conseil en migration Amazon EC2 :

* *Estimation du type d'instance* : migration Advisor peut désormais examiner les exigences de votre environnement et fournir un type d'instance Amazon EC2 estimé pour chaque machine virtuelle. Vous pouvez choisir d'inclure le type d'instance estimé pour chaque machine virtuelle pendant l'étape Scope de l'assistant de migration.
* *Possibilité de recommander des volumes Amazon EBS* : le conseiller en migration peut désormais recommander la migration des volumes de données vers Amazon Elastic Block Store (EBS) plutôt que vers Amazon FSX pour NetApp ONTAP en raison des besoins spécifiques en termes de capacité ou de performances d'une région donnée.
* *Attribution automatique améliorée du système de fichiers* : l'affectation du système de fichiers Amazon FSX pour NetApp ONTAP a été améliorée afin de mieux optimiser les coûts et de minimiser le débit.


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Créez un plan de déploiement pour Amazon EC2 à l'aide du conseiller de migration"]



=== Charges de travail GenAI



==== Améliorations du chatbot intégrées

Vous pouvez désormais copier des questions et des réponses directement dans le presse-papiers, ajuster la taille de la fenêtre de discussion et modifier son titre. De plus, les réponses de discussion peuvent maintenant inclure des tableaux, qui sont également copyables.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/test-knowledgebase.html["Testez une base de connaissances GenAI"]



==== Aide à la citation de réponse par chat

Les réponses à la discussion incluent maintenant des citations qui répertorient les fichiers et les segments de données utilisés pour générer la réponse.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/test-knowledgebase.html["Testez une base de connaissances GenAI"]



==== Prise en charge améliorée des types de fichiers

Cette version de GenAI fournit une prise en charge améliorée des fichiers :

* Les modèles de chat offrent une prise en charge CSV améliorée. Cela permet d'obtenir des réponses plus utiles lors de l'interrogation de données à partir de fichiers CSV.
* GenAI peut désormais ingérer des fichiers Apache parquet à partir de sources de données.
* GenAI prend désormais en charge l'ingestion de fichiers Microsoft Word DOCX contenant des images. Les images intégrées aux documents DOCX sont numérisées et les informations textuelles des images intégrées sont incluses dans les réponses aux requêtes de la base de connaissances.


link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/identify-data-sources-knowledge-base.html#supported-data-source-file-formats["Formats de fichiers de source de données pris en charge"]



== 2 février 2025



=== Configuration et administration



==== CloudShell est disponible dans la console d'usine des charges de travail BlueXP

CloudShell est disponible à partir de n'importe quel emplacement de la console d'usine de la charge de travail BlueXP . CloudShell vous permet d'utiliser les informations d'identification AWS et ONTAP que vous avez fournies dans votre compte BlueXP  et d'exécuter les commandes de la CLI AWS ou les commandes de la CLI ONTAP dans un environnement de type shell.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Utilisez CloudShell"]



==== Mise à jour des autorisations pour les bases de données

L'autorisation suivante est maintenant disponible en _read_ mode pour les bases de données : `iam:SimulatePrincipalPolicy`.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Journal des modifications de référence des autorisations"]
