---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: Découvrez les modifications les plus récentes apportées aux charges de travail qui font partie de NetApp Workload Factory. 
---
= Modifications récentes dans NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Découvrez les modifications les plus récentes apportées aux charges de travail qui font partie de NetApp Workload Factory.



== 01 février 2026



=== Workloads VMware



==== Analyse bien architecturée pour Amazon Elastic VMware Service

Workload Factory propose désormais une analyse automatisée bien architecturée de vos environnements Amazon Elastic VMware Service (EVS). Des analyses quotidiennes identifient les incohérences de configuration et offrent des recommandations de remédiation détaillées pour vous aider à maintenir des opérations, une sécurité et une efficacité des coûts optimales.

Les analyses sont effectuées à l'aide des API AWS—aucun identifiant vSphere ni connexion vCenter n'est requis. Les résultats sont disponibles dans le nouvel onglet *Well-architected status* des détails de votre environnement EVS.

Cette version inclut des informations sur :

* *État de la protection contre l'arrêt/la suppression des instances* : Identifie les nœuds EVS sans protection contre l'arrêt ou la suppression EC2. L'arrêt ou la suppression de nœuds EVS depuis la console EC2 peut entraîner l'indisponibilité des données de la machine virtuelle ou une perte de données.
* *Alignement du placement des partitions des nœuds du cluster* : détecte les désalignements de partitionnement susceptibles d’entraîner une perte de puissance de traitement importante ou une interruption en cas de défaillance d’une partition au sein d’une AWS Availability Zone. Chaque insight comprend des niveaux de gravité, des résultats détaillés avec des informations sur les ressources impactées et des procédures de correction étape par étape basées sur les bonnes pratiques AWS.


link:view-evs-well-architected.html["Mettre en œuvre des configurations bien architecturées"]



== 04 janvier 2026



=== Amazon FSX pour NetApp ONTAP



==== Mises à jour d'analyse bien conçues

Workload Factory analyse vos systèmes de fichiers FSx pour ONTAP pour les configurations suivantes :

* La protection autonome contre les ransomwares NetApp (ARP/AI) désactivée inclut les périphériques de stockage par blocs : vérifie si ARP/AI est désactivé sur les volumes de périphériques de stockage par blocs
* Mode d'écriture de la relation de cache : vérifie si le mode d'écriture est optimal pour la charge de travail du volume de cache.
* Suppression des sauvegardes inutiles : vérifie si les sauvegardes sont obsolètes ou inutiles et peuvent être supprimées pour réduire les coûts.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Affichez l'état bien architecturé de vos systèmes de fichiers FSx for ONTAP"]



==== Intégration de l'assistant IA à la page d'accueil de Ask me

La page d'accueil de la console Workload Factory intègre l'assistant IA Ask me, vous permettant de poser des questions sur votre propre infrastructure de stockage, d'obtenir des informations personnalisées directement à partir de votre environnement et de consulter les conversations précédentes. Vous pouvez interagir avec « Demandez-moi » pour comprendre vos charges de travail, résoudre les problèmes et en savoir plus sur Workload Factory, le tout sans quitter la console.



==== Utilisation du principal utilisateur IAM dans les stratégies d'autorisation basées sur les ressources de liaison Lambda

Les liens Lambda utilisés pour connecter votre compte Workload Factory à un ou plusieurs systèmes de fichiers FSx for ONTAP afin d'effectuer des opérations ONTAP avancées utilisent désormais le principal utilisateur IAM pour les autorisations de stratégie basées sur les ressources. Cette modification permet une meilleure adéquation avec les meilleures pratiques du secteur en matière d'accès aux ressources AWS.



==== Écran d'analyse ajouté pour l'analyseur IA des événements EMS

Un nouvel écran _Analyse_ a été ajouté au menu Stockage. À partir de cet écran, vous pouvez utiliser la fonctionnalité d'analyse IA pour les événements FSx for ONTAP EMS.



==== Améliorations apportées aux périphériques de stockage par blocs dans NetApp Workload Factory

Les améliorations suivantes ont été apportées aux périphériques de stockage par blocs.



===== Création de périphérique de blocage

NetApp Workload Factory prend en charge la création de périphériques de stockage par blocs utilisant le protocole iSCSI sur les systèmes de fichiers FSx pour ONTAP afin que vous puissiez mieux prendre en charge vos applications métier (LOB) depuis la console Workload Factory.



===== Améliorations de la gestion des périphériques de bloc

NetApp Workload Factory inclut les améliorations suivantes pour link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-devices.html["gestion des périphériques de stockage"]. Vous pouvez désormais effectuer les tâches suivantes depuis la console Workload Factory :

* Gérer l'accès client
* Données de bloc d'archivage
* Supprimer un périphérique de blocage




===== Prise en charge d'ARP/AI sur les volumes FlexVol contenant des périphériques de stockage par blocs

Vous pouvez activer link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["Protection autonome contre les ransomwares NetApp avec IA (ARP/AI)"] sur les volumes FlexVol contenant des périphériques de stockage par blocs. L'activation d'ARP/AI permet de détecter les attaques de ransomware grâce à l'IA et facilite la récupération des données.



=== Charges de travail des bases de données



==== Intégration de l'assistant IA à la page d'accueil de Ask me

La page d'accueil de la console Workload Factory intègre l'assistant IA Ask me, vous permettant de poser des questions sur votre propre infrastructure de stockage, d'obtenir des informations personnalisées directement à partir de votre environnement et de consulter les conversations précédentes. Vous pouvez interagir avec « Demandez-moi » pour comprendre vos charges de travail, résoudre les problèmes et en savoir plus sur Workload Factory, le tout sans quitter la console.



=== Workloads VMware



==== Intégration de l'assistant IA à la page d'accueil de Ask me

La page d'accueil de la console Workload Factory intègre l'assistant IA Ask me, vous permettant de poser des questions sur votre propre infrastructure de stockage, d'obtenir des informations personnalisées directement à partir de votre environnement et de consulter les conversations précédentes. Vous pouvez interagir avec « Demandez-moi » pour comprendre vos charges de travail, résoudre les problèmes et en savoir plus sur Workload Factory, le tout sans quitter la console.



=== Configuration et administration



==== Intégration de l'assistant IA à la page d'accueil de Ask me

La page d'accueil de la console Workload Factory intègre l'assistant IA Ask me, vous permettant de poser des questions sur votre propre infrastructure de stockage, d'obtenir des informations personnalisées directement à partir de votre environnement et de consulter les conversations précédentes. Vous pouvez interagir avec « Demandez-moi » pour comprendre vos charges de travail, résoudre les problèmes et en savoir plus sur Workload Factory, le tout sans quitter la console.



=== Charges de travail des constructeurs



==== NetApp Workload Factory for Builders devient NetApp Workload Factory for EDA

Workload Factory for Builders s'appelle désormais Workload Factory for EDA. Ce changement de nom reflète l'accent mis sur les charges de travail d'automatisation de la conception électronique (EDA).

Workload Factory pour EDA vous aide à optimiser FSx pour ONTAP sur plusieurs systèmes de fichiers. Vous pouvez optimiser les performances et réduire les coûts opérationnels en automatisant les paramètres de stockage, en analysant les contraintes de performance et en obtenant des informations sur les projets EDA. Workload Factory pour EDA est conçu pour s'intégrer à vos frameworks d'infrastructure en tant que code (IaC).



==== Intégration de l'assistant IA à la page d'accueil de Ask me

La page d'accueil de la console Workload Factory intègre l'assistant IA Ask me, vous permettant de poser des questions sur votre propre infrastructure de stockage, d'obtenir des informations personnalisées directement à partir de votre environnement et de consulter les conversations précédentes. Vous pouvez interagir avec « Demandez-moi » pour comprendre vos charges de travail, résoudre les problèmes et en savoir plus sur Workload Factory, le tout sans quitter la console.



== 18 décembre 2025



=== Charges de travail des bases de données



==== Améliorations de l'intégration d'Active Directory

Workload Factory for Databases inclut trois nouveaux champs Active Directory (AD) lors du déploiement de Microsoft SQL Server à l'aide de l'option *Création avancée*. Ces améliorations vous permettent de spécifier les préférences de jonction à Active Directory et d'utiliser un compte de service géré.

Les nouveaux champs AD sont :

* Contrôleur de domaine préféré
* Parcours privilégié au sein de l'unité organisationnelle
* Groupe Active Directory cible


link:https://docs.netapp.com/us-en/workload-databases/create-database.html["Déployer Microsoft SQL Server"]



== 4 décembre 2025



=== Amazon FSX pour NetApp ONTAP



==== Prise en charge des points d'accès AWS S3 pour FSx for ONTAP

NetApp Workload Factory prend en charge les points d'accès AWS S3 pour vos systèmes de fichiers FSx for ONTAP . Vous pouvez créer des volumes à l'aide de points d'accès S3, attribuer des points d'accès S3 à un volume existant et gérer les points d'accès S3 depuis la console Workload Factory. En utilisant un point d'accès S3, vous pouvez accéder aux données de fichiers résidant sur des volumes SMB/CIFS ou NFS via les API AWS S3. Cela vous permet d'intégrer vos données existantes avec GenAI, ML et les analyses des services AWS qui prennent en charge les points d'accès S3.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Créer un volume à l'aide de points d'accès S3"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-s3-access-points.html["Gérer les points d'accès S3 pour un volume"]




== 27 novembre 2025



=== Amazon FSX pour NetApp ONTAP



==== Prise en charge des périphériques de stockage dans NetApp Workload Factory

Gérez plus efficacement vos périphériques de stockage par blocs grâce à la nouvelle prise en charge des périphériques de stockage par blocs dans NetApp Workload Factory. Cette fonctionnalité vous permet de consulter les détails et d'augmenter la capacité des LUN iSCSI, offrant ainsi une flexibilité accrue pour vos besoins de stockage.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-devices.html["Gérer les périphériques de stockage par blocs dans Workload Factory"]



==== Mises à jour d'analyse bien conçues

Workload Factory analyse vos systèmes de fichiers FSx pour ONTAP pour les configurations suivantes :

* Suppression des snapshots inutiles : vérifie si les volumes contiennent des snapshots obsolètes et inutiles pouvant être supprimés afin de réduire les coûts.
* Rééquilibrage des volumes FlexGroup : vérifie si les volumes FlexGroup sont répartis uniformément entre leurs membres afin de garantir des performances optimales.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Affichez l'état bien architecturé de vos systèmes de fichiers FSx for ONTAP"]



==== Analyseur d'IA pour les événements EMS dans NetApp Workload Factory

NetApp Workload Factory introduit un analyseur basé sur l'IA pour les événements du système de gestion des événements ONTAP (EMS). Cette fonctionnalité vous aide à identifier et à résoudre rapidement les problèmes en fournissant des informations et des recommandations basées sur l'analyse des données des événements des services d'urgence médicale.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/analyze-events.html["Analyser les événements EMS dans Workload Factory"]



==== Surveiller les tendances en matière de coûts et d'utilisation des systèmes de fichiers FSx pour ONTAP

Vous pouvez suivre les tendances en matière de coûts et d'utilisation de vos systèmes de fichiers FSx pour ONTAP directement depuis la console NetApp Workload Factory . Cette fonctionnalité fournit des indicateurs de consommation et de coût de stockage ainsi que des coûts détaillés, vous aidant ainsi à optimiser l'allocation de vos ressources et la planification de votre budget.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/track-costs.html["Suivez les coûts des systèmes de fichiers FSx pour ONTAP dans Workload Factory"]



==== Gérer les balises FSx pour un système de fichiers dans NetApp Workload Factory

Gérez facilement vos balises FSx pour un système de fichiers directement depuis la console NetApp Workload Factory . Cette fonctionnalité vous permet d'ajouter, de modifier ou de supprimer des balises, ce qui permet une meilleure organisation et catégorisation de vos systèmes de fichiers FSx pour ONTAP .

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-fsx-tags.html["Gérer les balises FSx dans Workload Factory"]



==== Ajuster la capacité du cache pour les systèmes de fichiers FSx pour ONTAP

Vous pouvez augmenter ou diminuer la capacité des volumes de cache depuis la console Workload Factory.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-cache-volumes.html["Gérer les volumes de cache dans Workload Factory"]



=== Charges de travail des bases de données



==== Optimisez vos économies grâce au calculateur de bases de données pour Amazon Elastic Block Store (EBS)

Deux nouvelles fonctionnalités du calculateur améliorent l'analyse des économies réalisées lors de l'exécution de plusieurs instances avec un stockage EBS, ce qui vous permet d'économiser davantage en passant à FSx pour ONTAP.

* Workload Factory fournit une solution de stockage consolidée pour plusieurs hôtes de bases de données sur un seul système de fichiers FSx pour ONTAP . Cette consolidation optimise les coûts de stockage en réduisant le nombre de systèmes de fichiers nécessaires pour plusieurs hôtes de bases de données, ce qui permet de réaliser des économies substantielles.
* Workload Factory analyse votre utilisation des performances EBS et vous suggère ensuite la configuration FSx pour ONTAP la plus performante et la plus économique.


link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html#explore-savings-for-detected-hosts["Découvrez les économies possibles pour les hôtes EBS détectés"]



==== Rapport Excel disponible pour le tableau de bord bien conçu

Vous pouvez télécharger un rapport Excel du tableau de bord bien conçu. Le rapport fournit l'état bien architecturé de la ressource de base de données et des recommandations pour toutes les configurations de ressources, y compris les sous-configurations pour le système d'exploitation et ONTAP.



==== Analyseur de journaux d'erreurs disponible pour les bases de données Oracle

L'analyseur de journaux d'erreurs Agentic, basé sur l'IA, est disponible pour les bases de données Oracle. Cette fonctionnalité exploite des algorithmes d'apprentissage automatique avancés pour détecter et analyser automatiquement les erreurs dans les fichiers journaux. Cet outil vise à rationaliser le processus de dépannage en fournissant aux développeurs des informations et des recommandations exploitables basées sur les modèles qu'il identifie dans les journaux.

link:https://docs.netapp.com/us-en/workload-databases/analyze-error-logs.html["En savoir plus sur l'analyseur de journaux d'erreurs basé sur l'IA Agentic"]



==== Analyse bien architecturée pour Oracle

L'analyse, bien conçue, inclut deux nouvelles configurations de dimensionnement du stockage. L'analyse évalue et corrige les problèmes de configuration liés à l'allocation d'espace d'échange et à la marge de manœuvre du système de fichiers pour les déploiements de bases de données Oracle existants.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implémenter des configurations de base de données bien architecturées dans Workload Factory"]



=== Workloads VMware



==== Calculez les économies réalisées grâce à la migration vers Amazon Elastic VMware Service pour des régions spécifiques.

Vous pouvez désormais explorer la valeur des différentes options de déploiement pour votre migration vers le cloud, optimiser les efforts investis dans l'évaluation des solutions et examiner en profondeur les solutions susceptibles de générer de la valeur et des économies dans le cloud.

Vous pouvez également consulter les économies de cœurs vCPU réalisables grâce à l'utilisation de FSx pour ONTAP dans le cadre d'un déploiement EVS.

https://docs.netapp.com/us-en/workload-vmware/calculate-evs-savings.html["Découvrez les économies réalisées sur Amazon Elastic VMware Service avec NetApp Workload Factory"]



=== Configuration et administration



==== Mise à jour des autorisations pour le stockage

L'analyseur d'événements FSx pour ONTAP EMS utilise les autorisations Amazon Bedrock suivantes dans la stratégie d'autorisation _opérations et correction_ pour récupérer les données d'événements de la charge de travail de stockage.

* `bedrock:ListInferenceProfiles`
* `bedrock:GetInferenceProfile`
* `bedrock:InvokeModelWithResponseStream`
* `bedrock:InvokeModel`


link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Journal des modifications de référence des autorisations"]
