---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: Découvrez les modifications les plus récentes apportées aux charges de travail qui font partie de NetApp Workload Factory. 
---
= Modifications récentes dans NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Découvrez les modifications les plus récentes apportées aux charges de travail qui font partie de NetApp Workload Factory.



== 04 janvier 2026



=== Amazon FSX pour NetApp ONTAP



==== Mises à jour d'analyse bien conçues

Workload Factory analyse vos systèmes de fichiers FSx pour ONTAP pour les configurations suivantes :

* La protection autonome contre les ransomwares NetApp (ARP/AI) désactivée inclut les périphériques de stockage par blocs : vérifie si ARP/AI est désactivé sur les volumes de périphériques de stockage par blocs
* Mode d'écriture de la relation de cache : vérifie si le mode d'écriture est optimal pour la charge de travail du volume de cache.
* Suppression des sauvegardes inutiles : vérifie si les sauvegardes sont obsolètes ou inutiles et peuvent être supprimées pour réduire les coûts.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Affichez l'état bien architecturé de vos systèmes de fichiers FSx for ONTAP"]



==== Intégration de l'assistant IA à la page d'accueil de Ask me

La page d'accueil de la console Workload Factory intègre l'assistant IA Ask me, vous permettant de poser des questions sur votre propre infrastructure de stockage, d'obtenir des informations personnalisées directement à partir de votre environnement et de consulter les conversations précédentes. Vous pouvez interagir avec « Demandez-moi » pour comprendre vos charges de travail, résoudre les problèmes et en savoir plus sur Workload Factory, le tout sans quitter la console.



==== Utilisation du principal utilisateur IAM dans les stratégies d'autorisation basées sur les ressources de liaison Lambda

Les liens Lambda utilisés pour connecter votre compte Workload Factory à un ou plusieurs systèmes de fichiers FSx for ONTAP afin d'effectuer des opérations ONTAP avancées utilisent désormais le principal utilisateur IAM pour les autorisations de stratégie basées sur les ressources. Cette modification permet une meilleure adéquation avec les meilleures pratiques du secteur en matière d'accès aux ressources AWS.



==== Écran d'analyse ajouté pour l'analyseur IA des événements EMS

Un nouvel écran _Analyse_ a été ajouté au menu Stockage. À partir de cet écran, vous pouvez utiliser la fonctionnalité d'analyse IA pour les événements FSx for ONTAP EMS.



==== Améliorations apportées aux périphériques de stockage par blocs dans NetApp Workload Factory

Les améliorations suivantes ont été apportées aux périphériques de stockage par blocs.



===== Création de périphérique de blocage

NetApp Workload Factory prend en charge la création de périphériques de stockage par blocs utilisant le protocole iSCSI sur les systèmes de fichiers FSx pour ONTAP afin que vous puissiez mieux prendre en charge vos applications métier (LOB) depuis la console Workload Factory.



===== Améliorations de la gestion des périphériques de bloc

NetApp Workload Factory inclut les améliorations suivantes pour link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-devices.html["gestion des périphériques de stockage"]. Vous pouvez désormais effectuer les tâches suivantes depuis la console Workload Factory :

* Gérer l'accès client
* Données de bloc d'archivage
* Supprimer un périphérique de blocage




===== Prise en charge d'ARP/AI sur les volumes FlexVol contenant des périphériques de stockage par blocs

Vous pouvez activer link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["Protection autonome contre les ransomwares NetApp avec IA (ARP/AI)"] sur les volumes FlexVol contenant des périphériques de stockage par blocs. L'activation d'ARP/AI permet de détecter les attaques de ransomware grâce à l'IA et facilite la récupération des données.



=== Charges de travail des bases de données



==== Intégration de l'assistant IA à la page d'accueil de Ask me

La page d'accueil de la console Workload Factory intègre l'assistant IA Ask me, vous permettant de poser des questions sur votre propre infrastructure de stockage, d'obtenir des informations personnalisées directement à partir de votre environnement et de consulter les conversations précédentes. Vous pouvez interagir avec « Demandez-moi » pour comprendre vos charges de travail, résoudre les problèmes et en savoir plus sur Workload Factory, le tout sans quitter la console.



=== Workloads VMware



==== Intégration de l'assistant IA à la page d'accueil de Ask me

La page d'accueil de la console Workload Factory intègre l'assistant IA Ask me, vous permettant de poser des questions sur votre propre infrastructure de stockage, d'obtenir des informations personnalisées directement à partir de votre environnement et de consulter les conversations précédentes. Vous pouvez interagir avec « Demandez-moi » pour comprendre vos charges de travail, résoudre les problèmes et en savoir plus sur Workload Factory, le tout sans quitter la console.



== 18 décembre 2025



=== Charges de travail des bases de données



==== Améliorations de l'intégration d'Active Directory

Workload Factory for Databases inclut trois nouveaux champs Active Directory (AD) lors du déploiement de Microsoft SQL Server à l'aide de l'option *Création avancée*. Ces améliorations vous permettent de spécifier les préférences de jonction à Active Directory et d'utiliser un compte de service géré.

Les nouveaux champs AD sont :

* Contrôleur de domaine préféré
* Parcours privilégié au sein de l'unité organisationnelle
* Groupe Active Directory cible


link:https://docs.netapp.com/us-en/workload-databases/create-database.html["Déployer Microsoft SQL Server"]



== 4 décembre 2025



=== Amazon FSX pour NetApp ONTAP



==== Prise en charge des points d'accès AWS S3 pour FSx for ONTAP

NetApp Workload Factory prend en charge les points d'accès AWS S3 pour vos systèmes de fichiers FSx for ONTAP . Vous pouvez créer des volumes à l'aide de points d'accès S3, attribuer des points d'accès S3 à un volume existant et gérer les points d'accès S3 depuis la console Workload Factory. En utilisant un point d'accès S3, vous pouvez accéder aux données de fichiers résidant sur des volumes SMB/CIFS ou NFS via les API AWS S3. Cela vous permet d'intégrer vos données existantes avec GenAI, ML et les analyses des services AWS qui prennent en charge les points d'accès S3.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Créer un volume à l'aide de points d'accès S3"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-s3-access-points.html["Gérer les points d'accès S3 pour un volume"]




== 27 novembre 2025



=== Amazon FSX pour NetApp ONTAP



==== Prise en charge des périphériques de stockage dans NetApp Workload Factory

Gérez plus efficacement vos périphériques de stockage par blocs grâce à la nouvelle prise en charge des périphériques de stockage par blocs dans NetApp Workload Factory. Cette fonctionnalité vous permet de consulter les détails et d'augmenter la capacité des LUN iSCSI, offrant ainsi une flexibilité accrue pour vos besoins de stockage.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-devices.html["Gérer les périphériques de stockage par blocs dans Workload Factory"]



==== Mises à jour d'analyse bien conçues

Workload Factory analyse vos systèmes de fichiers FSx pour ONTAP pour les configurations suivantes :

* Suppression des snapshots inutiles : vérifie si les volumes contiennent des snapshots obsolètes et inutiles pouvant être supprimés afin de réduire les coûts.
* Rééquilibrage des volumes FlexGroup : vérifie si les volumes FlexGroup sont répartis uniformément entre leurs membres afin de garantir des performances optimales.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Affichez l'état bien architecturé de vos systèmes de fichiers FSx for ONTAP"]



==== Analyseur d'IA pour les événements EMS dans NetApp Workload Factory

NetApp Workload Factory introduit un analyseur basé sur l'IA pour les événements du système de gestion des événements ONTAP (EMS). Cette fonctionnalité vous aide à identifier et à résoudre rapidement les problèmes en fournissant des informations et des recommandations basées sur l'analyse des données des événements des services d'urgence médicale.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/analyze-events.html["Analyser les événements EMS dans Workload Factory"]



==== Surveiller les tendances en matière de coûts et d'utilisation des systèmes de fichiers FSx pour ONTAP

Vous pouvez suivre les tendances en matière de coûts et d'utilisation de vos systèmes de fichiers FSx pour ONTAP directement depuis la console NetApp Workload Factory . Cette fonctionnalité fournit des indicateurs de consommation et de coût de stockage ainsi que des coûts détaillés, vous aidant ainsi à optimiser l'allocation de vos ressources et la planification de votre budget.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/track-costs.html["Suivez les coûts des systèmes de fichiers FSx pour ONTAP dans Workload Factory"]



==== Gérer les balises FSx pour un système de fichiers dans NetApp Workload Factory

Gérez facilement vos balises FSx pour un système de fichiers directement depuis la console NetApp Workload Factory . Cette fonctionnalité vous permet d'ajouter, de modifier ou de supprimer des balises, ce qui permet une meilleure organisation et catégorisation de vos systèmes de fichiers FSx pour ONTAP .

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-fsx-tags.html["Gérer les balises FSx dans Workload Factory"]



==== Ajuster la capacité du cache pour les systèmes de fichiers FSx pour ONTAP

Vous pouvez augmenter ou diminuer la capacité des volumes de cache depuis la console Workload Factory.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-cache-volumes.html["Gérer les volumes de cache dans Workload Factory"]



=== Charges de travail des bases de données



==== Optimisez vos économies grâce au calculateur de bases de données pour Amazon Elastic Block Store (EBS)

Deux nouvelles fonctionnalités du calculateur améliorent l'analyse des économies réalisées lors de l'exécution de plusieurs instances avec un stockage EBS, ce qui vous permet d'économiser davantage en passant à FSx pour ONTAP.

* Workload Factory fournit une solution de stockage consolidée pour plusieurs hôtes de bases de données sur un seul système de fichiers FSx pour ONTAP . Cette consolidation optimise les coûts de stockage en réduisant le nombre de systèmes de fichiers nécessaires pour plusieurs hôtes de bases de données, ce qui permet de réaliser des économies substantielles.
* Workload Factory analyse votre utilisation des performances EBS et vous suggère ensuite la configuration FSx pour ONTAP la plus performante et la plus économique.


link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html#explore-savings-for-detected-hosts["Découvrez les économies possibles pour les hôtes EBS détectés"]



==== Rapport Excel disponible pour le tableau de bord bien conçu

Vous pouvez télécharger un rapport Excel du tableau de bord bien conçu. Le rapport fournit l'état bien architecturé de la ressource de base de données et des recommandations pour toutes les configurations de ressources, y compris les sous-configurations pour le système d'exploitation et ONTAP.



==== Analyseur de journaux d'erreurs disponible pour les bases de données Oracle

L'analyseur de journaux d'erreurs Agentic, basé sur l'IA, est disponible pour les bases de données Oracle. Cette fonctionnalité exploite des algorithmes d'apprentissage automatique avancés pour détecter et analyser automatiquement les erreurs dans les fichiers journaux. Cet outil vise à rationaliser le processus de dépannage en fournissant aux développeurs des informations et des recommandations exploitables basées sur les modèles qu'il identifie dans les journaux.

link:https://docs.netapp.com/us-en/workload-databases/analyze-error-logs.html["En savoir plus sur l'analyseur de journaux d'erreurs basé sur l'IA Agentic"]



==== Analyse bien architecturée pour Oracle

L'analyse, bien conçue, inclut deux nouvelles configurations de dimensionnement du stockage. L'analyse évalue et corrige les problèmes de configuration liés à l'allocation d'espace d'échange et à la marge de manœuvre du système de fichiers pour les déploiements de bases de données Oracle existants.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implémenter des configurations de base de données bien architecturées dans Workload Factory"]



=== Workloads VMware



==== Calculez les économies réalisées grâce à la migration vers Amazon Elastic VMware Service pour des régions spécifiques.

Vous pouvez désormais explorer la valeur des différentes options de déploiement pour votre migration vers le cloud, optimiser les efforts investis dans l'évaluation des solutions et examiner en profondeur les solutions susceptibles de générer de la valeur et des économies dans le cloud.

Vous pouvez également consulter les économies de cœurs vCPU réalisables grâce à l'utilisation de FSx pour ONTAP dans le cadre d'un déploiement EVS.

https://docs.netapp.com/us-en/workload-vmware/calculate-evs-savings.html["Découvrez les économies réalisées sur Amazon Elastic VMware Service avec NetApp Workload Factory"]



=== Configuration et administration



==== Mise à jour des autorisations pour le stockage

L'analyseur d'événements FSx pour ONTAP EMS utilise les autorisations Amazon Bedrock suivantes dans la stratégie d'autorisation _opérations et correction_ pour récupérer les données d'événements de la charge de travail de stockage.

* `bedrock:ListInferenceProfiles`
* `bedrock:GetInferenceProfile`
* `bedrock:InvokeModelWithResponseStream`
* `bedrock:InvokeModel`


link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Journal des modifications de référence des autorisations"]



== 02 novembre 2025



=== Amazon FSX pour NetApp ONTAP



==== Gestion du volume du cache

Vous pouvez effectuer les opérations de gestion des volumes de cache suivantes depuis la console Workload Factory :

* Modifier le nom du cache
* Augmenter la capacité d'un volume de cache
* Modifiez le chemin de montage ou la stratégie d'exportation d'un volume de cache.
* Modifier la méthode de mise en cache, ou le mode, d'un volume de cache
* Préremplir un volume de cache
* Supprimer un volume de cache


link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-cache-volumes.html["Gérer les volumes de cache"]



==== Gestion automatique des inodes disponible

Vous pouvez activer la gestion automatique des inodes sans avoir besoin d'activer la gestion automatique de la capacité.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html["Activer la gestion automatique des inodes"]



==== Paramètre d'alerte de seuil pour l'utilisation de la capacité et des inodes

Des alertes de seuil sont disponibles pour la capacité et l'utilisation des inodes. Vous pouvez définir ces seuils lors de l'activation de la gestion automatique de la capacité ou des inodes. Pour utiliser ce paramètre, vous devrez configurer les notifications à l'aide delink:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Service de notification NetApp Workload Factory"^] .



==== Réduction de volume disponible

Vous pouvez réduire la taille des volumes NFS et SMB/CIFS dans NetApp Workload Factory. Cette fonctionnalité permet une meilleure gestion des ressources de stockage en vous permettant de réduire la taille des volumes qui ne sont plus nécessaires à leur capacité actuelle.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/adjust-volume-capacity.html["Diminuer la capacité d'un volume"]



==== État de ressource FSx amélioré pour ONTAP

Workload Factory a amélioré l'état de ressource « mal configurée » afin d'inclure une explication du problème réel rencontré avec la ressource.



==== Mises à jour d'analyse bien conçues

Workload Factory analyse vos systèmes de fichiers FSx pour ONTAP pour les configurations suivantes :

* Utilisation des volumes proche de la saturation : vérifie si des volumes utilisent 80 % ou plus de leur capacité de fichiers. Cela vous permet d'identifier les volumes qui pourraient nécessiter une capacité supplémentaire.
* Accès non autorisé aux volumes : vérifie si un volume iSCSI est accessible via un chemin de montage NFS ou SMB/CIFS et vous permet de supprimer tout accès non autorisé au volume afin d’éviter les risques de sécurité.




==== Modifications des autorisations pour Workload Factory pour le stockage

Workload Factory offre une plus grande clarté quant aux autorisations requises pour des actions spécifiques et une granularité permettant de sélectionner uniquement les autorisations nécessaires. Lorsque vous ajouterez des informations d'identification, vous aurez le choix entre trois options d'autorisation au lieu du modèle d'autorisation précédent qui était _lecture seule_ et _lecture/écriture_. Le nouveau modèle d'autorisations décompose les politiques d'autorisation comme suit :

* _Visualisation, planification et analyse_ : visualisez les systèmes de fichiers FSx pour ONTAP , informez-vous sur l’état du système, obtenez une analyse bien architecturée de vos systèmes et explorez les économies possibles.
* _Opérations et correction_ : Effectuez des tâches opérationnelles telles que l'ajustement de la capacité du système de fichiers et la résolution des problèmes liés à la configuration de votre système de fichiers.
* _Création et suppression de systèmes de fichiers_ : Créez et supprimez des systèmes de fichiers FSx pour ONTAP et des machines virtuelles de stockage.


Lors de l'ajout d'identifiants, vous pouvez sélectionner une ou plusieurs de ces stratégies d'autorisation en fonction du niveau d'accès que vous souhaitez accorder à Workload Factory.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Référence des autorisations de Workload Factory"]



==== Prise en charge de FSx pour ONTAP Cyber ​​Vault

Vous pouvez créer un coffre-fort numérique en utilisant FSx for ONTAP comme source ou cible dans l'architecture du coffre-fort numérique. Les coffres-forts numériques offrent un environnement sécurisé et isolé pour le stockage des données critiques, les protégeant ainsi des ransomwares et autres cybermenaces.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-cyber-vault.html["Configurer un coffre-fort numérique avec FSx pour ONTAP"]



=== Charges de travail des bases de données



==== Améliorations du tableau de bord

Le nouveau tableau de bord est simplifié et mieux organisé pour offrir une vue d'ensemble plus claire de vos ressources de base de données et des fonctionnalités clés de Workload Factory sur un seul écran ; une carte met en évidence les ressources de base de données, une carte fournit des informations sur le score et l'analyse de l'architecture, une carte affiche l'analyse des erreurs, deux cartes affichent le coût mensuel et les économies potentielles, et une carte affiche des informations sur les environnements de test.



==== Analyse bien architecturée pour Oracle

L'analyse bien conçue comprend les évaluations et les correctifs suivants pour les configurations Oracle :

* Système d'exploitation de configuration de stockage utilisant le protocole NFS : évalue et corrige les problèmes de configuration NFS pour les déploiements de bases de données Oracle existants.
* Système d'exploitation de configuration de stockage utilisant le protocole iSCSI : évalue et corrige les problèmes de configuration iSCSI pour les déploiements de bases de données Oracle existants.
* Système d'exploitation de configuration de stockage utilisant Automatic Storage Management (ASM) : évalue les problèmes de configuration avec la configuration ASM pour les déploiements de bases de données Oracle existants.


link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implémenter des configurations de base de données bien architecturées dans Workload Factory"]



==== Modifications des autorisations pour Workload Factory pour les bases de données

Workload Factory for Databases a mis à jour les politiques d'autorisation afin de clarifier les exigences pour des actions spécifiques et d'offrir une granularité permettant de sélectionner uniquement les autorisations nécessaires. Lorsque vous ajouterez des informations d'identification, vous aurez le choix entre trois options d'autorisation au lieu du modèle d'autorisation précédent qui était _lecture seule_ et _lecture/écriture_. Le nouveau modèle d'autorisations décompose les politiques d'autorisation comme suit :

* Visualisation, planification et analyse : consultez l’inventaire des ressources de votre base de données, évaluez leur état, examinez l’analyse de l’architecture de vos configurations, accédez à l’analyse des journaux d’erreurs et explorez les économies potentielles.
* _Opérations et correction_ : effectuez les tâches opérationnelles liées à vos ressources de base de données et corrigez les problèmes de configuration de la base de données et du système de stockage de fichiers FSx pour ONTAP sous-jacent.
* _Création d'hôtes de base de données_ : déployer les hôtes de base de données et le système de stockage de fichiers FSx pour ONTAP sous-jacent conformément aux meilleures pratiques


Lors de l'ajout d'informations d'identification, vous pouvez sélectionner une ou plusieurs de ces stratégies d'autorisation en fonction du niveau d'accès que vous souhaitez accorder à Workload Factory for Databases.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Référence des autorisations de Workload Factory"^]



==== Écran de tableau de bord bien conçu ajouté

Un nouvel écran de tableau de bord _bien conçu_ a été ajouté au menu Bases de données. Cet écran vous permet d'obtenir une vue d'ensemble de l'état de configuration de l'ensemble de votre parc de bases de données.



==== Protection des modifications pour les déploiements de bases de données dans NetApp Backup and Recovery

Depuis la console Workload Factory, vous pouvez sélectionner l'option permettant de modifier la protection d'une ressource protégée, puis vous serez redirigé vers la section Sauvegarde et restauration de la NetApp Console où vous pourrez modifier la stratégie ou la planification de protection.

link:https://docs.netapp.com/us-en/workload-databases/protect-sql-server.html["Protection contre la modification pour les déploiements de bases de données"]



==== Le filtrage des erreurs par étiquettes est disponible pour la fonction d'analyse des erreurs.

Vous pouvez filtrer et afficher les journaux d'erreurs de Microsoft SQL Server par balises orientées infrastructure lorsque vous utilisez la fonctionnalité d'analyse des erreurs dans Workload Factory. Cette amélioration vous permet de trier, de dépanner et de résoudre rapidement les problèmes.

link:https://docs.netapp.com/us-en/workload-databases/analyze-error-logs.html["Analyser les journaux d'erreurs avec filtrage par étiquette"^]



=== Workloads VMware



==== Présentation des préférences d'Amazon Elastic VMware Service dans l'assistant de déploiement du système de fichiers FSx pour ONTAP

Lorsque vous déployez un système de fichiers FSx for ONTAP destiné à être utilisé comme banque de données NFS externe pour Amazon Elastic VMware Service, vous pouvez désormais sélectionner l'environnement EVS auquel les banques de données seront connectées. Cela permet de remplir automatiquement plusieurs champs de l'assistant de déploiement afin de simplifier le processus de déploiement.

https://docs.netapp.com/us-en/workload-vmware/deploy-fsx-file-system-evs.html["Déployez le système de fichiers FSx recommandé pour ONTAP"]



==== Modifications des autorisations pour les charges de travail VMware

VMware Workloads offre une meilleure visibilité sur les autorisations requises pour des actions spécifiques et une granularité permettant de sélectionner uniquement les autorisations nécessaires. Lorsque vous ajouterez des informations d'identification, vous aurez le choix entre deux options d'autorisation au lieu du modèle d'autorisation précédent qui était _lecture seule_ et _lecture/écriture_. Le nouveau modèle d'autorisations décompose les politiques d'autorisation comme suit :

* _Visualisation, planification et analyse_ : Consultez l’inventaire des environnements de virtualisation EVS, obtenez une analyse détaillée de vos systèmes et explorez les économies possibles.
* _Déploiement et connectivité des datastores_ : Déployez les configurations de machines virtuelles recommandées sur les clusters Amazon EVS, Amazon EC2 ou VMware Cloud on AWS vSphere et utilisez des systèmes de fichiers Amazon FSx for NetApp ONTAP comme datastores externes.


Lors de l'ajout d'informations d'identification, vous pouvez sélectionner une ou plusieurs de ces stratégies d'autorisation en fonction du niveau d'accès que vous souhaitez accorder aux charges de travail VMware.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Référence des autorisations de Workload Factory"^]



==== Améliorations de l'assistant de migration Amazon EC2

Cette version de NetApp Workload Factory pour VMware apporte plusieurs améliorations à l'expérience du conseiller de migration :

* *Enregistrer ou télécharger un plan de migration* : Vous pouvez désormais enregistrer ou télécharger un plan de migration au format PDF ou CSV. Lorsque vous enregistrez un plan de migration, celui-ci est enregistré sur votre compte Workload Factory.




=== Configuration et administration



==== Mise à jour des autorisations

Dans cette version, nous avons apporté des mises à jour importantes aux politiques d'autorisation pour le stockage, les bases de données et les charges de travail VMware afin d'améliorer la sécurité et le contrôle des utilisateurs. Vous pouvez personnaliser vos paramètres d'autorisation de manière plus précise, en ajoutant ou en supprimant des autorisations selon vos besoins.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Référence des autorisations pour Workload Factory"]



==== Nouvelle notification pour le stockage

Le service de notification NetApp Workload Factory inclut la notification pour la gestion automatique des inodes pour le stockage.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Notifications pour NetApp Workload Factory"]



==== Avertissements de seuil pour la gestion automatique de la capacité et des inodes

La gestion automatique de la capacité et des inodes pour le stockage peut être configurée avec un seuil d'alerte qui déclenche une notification du service de notification Workload Factory. Pour utiliser cette fonctionnalité, vous devez d'abord activer le service de notification Workload Factory.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Configurer les notifications pour NetApp Workload Factory"]
