= Optimisez en continu vos workloads Microsoft SQL Server avec les bases de données
:allow-uri-read: 




=== Optimisez en continu vos workloads Microsoft SQL Server avec les bases de données

La fabrique de workloads BlueXP  propose des conseils continus et des rambardes afin d'assurer une optimisation continue et le respect des meilleures pratiques pour le composant de stockage de vos workloads Microsoft SQL Server sur Amazon FSX pour NetApp ONTAP. Cette fonctionnalité analyse en continu votre environnement Microsoft SQL Server hors ligne et vous fournit un rapport complet d'informations, d'opportunités et de recommandations pour vous aider à atteindre des niveaux de performance, de rentabilité et de conformité élevés.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Optimisez vos workloads SQL Server"]



=== Prise en charge de Terraform

Vous pouvez maintenant utiliser Terraform à partir de la Codebox pour déployer Microsoft SQL Server.

* link:https://docs.netapp.com/us-en/workload-databases/create-database-server.html["Créez un serveur de base de données"^]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["Utiliser Terraform à partir de Codebox"^]

