= Prise en charge du mode de lecture pour la gestion du stockage
:allow-uri-read: 




=== Prise en charge du mode de lecture pour la gestion du stockage

Le mode de lecture est disponible pour la gestion du stockage en usine des charges de travail. Le mode lecture améliore l'expérience du mode de base en ajoutant des autorisations en lecture seule afin que les modèles Infrastructure-as-Code soient remplis avec vos variables spécifiques. Les modèles Infrastructure-as-Code peuvent être exécutés directement depuis votre compte AWS sans permissions de modification pour l'usine des workloads.

link:https://docs.netapp.com/us-en/workload-setup-admin/operational-modes.html["En savoir plus sur le mode lecture"]



=== Prise en charge de la sauvegarde avant suppression de volume

Vous pouvez à présent sauvegarder un volume avant de le supprimer. La sauvegarde restera dans le système de fichiers jusqu'à sa suppression.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/delete-volume.html["Supprimer un volume"]
