= La BlueXP backup and recovery prennent désormais en charge la charge de travail Microsoft SQL Server
:allow-uri-read: 




=== La BlueXP backup and recovery prennent désormais en charge la charge de travail Microsoft SQL Server

La BlueXP backup and recovery vous permettent de sauvegarder, restaurer, vérifier et cloner des bases de données et des groupes de disponibilité Microsoft SQL Server. À partir de la console de l’usine de charge de travail, vous pouvez accéder et utiliser la BlueXP backup and recovery pour protéger les charges de travail Microsoft SQL Server.

link:https://docs.netapp.com/us-en/workload-databases/protect-sql-server.html["Découvrez comment protéger les charges de travail Microsoft SQL Server via la console Workload Factory"] .

Pour plus de détails sur la BlueXP backup and recovery, reportez-vous aulink:https://docs.netapp.com/us-en/bluexp-backup-recovery/br-use-mssql-protect-overview.html["Présentation de la protection des charges de travail Microsoft SQL avec la BlueXP backup and recovery"^] .
