= Protection anti-ransomware autonome pour les systèmes de fichiers FSX pour ONTAP
:allow-uri-read: 




=== Protection anti-ransomware autonome pour les systèmes de fichiers FSX pour ONTAP

Protégez vos données avec la protection anti-ransomware autonome (ARP), une fonctionnalité qui utilise l'analyse des workloads dans les environnements NAS (NFS/SMB) pour détecter et signaler les activités anormales qui pourraient être une attaque par ransomware. Lorsqu'une attaque est suspectée, ARP crée également de nouveaux snapshots immuables à partir desquels vous pouvez restaurer vos données.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["Protégez vos données avec la protection anti-ransomware autonome"]



=== Amélioration du rééquilibrage des volumes FlexGroup

BlueXP  Workload Factory lance l'assistant de rééquilibrage des volumes FlexGroup avec plusieurs options de disposition pour le rééquilibrage des données dans un volume FlexGroup. Le rééquilibrage redistribue les données de façon homogène vers les volumes de membres FlexGroup.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/rebalance-volume.html["Rééquilibrez la capacité d'un volume FlexGroup"]



=== Implémentez les bonnes pratiques pour un système de fichiers FSX pour ONTAP

La fabrique de charges de travail BlueXP  fournit un tableau de bord dans lequel vous pouvez consulter l'état de l'architecture de vos configurations de système de fichiers. Cette analyse vous permet d'implémenter les bonnes pratiques pour vos systèmes de fichiers FSX pour ONTAP. L'analyse de la configuration du système de fichiers comprend les configurations suivantes : seuil de capacité SSD, snapshots locaux programmés, sauvegardes FSX pour ONTAP, Tiering des données et réplication des données à distance.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html["En savoir plus sur l'analyse bien conçue pour les configurations de système de fichiers"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Implémentez les meilleures pratiques pour vos systèmes de fichiers"]




=== Options de type de sécurité des volumes à double protocole

Vous avez la possibilité de choisir NTFS ou UNIX comme style de sécurité pour un volume afin de déterminer la méthode d'accès des utilisateurs et des autorisations à un volume.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Créer un volume"]



=== Amélioration de la réplication



==== Réplication inverse prise en charge à partir de FSX pour ONTAP vers l'environnement sur site

La réplication inverse est désormais disponible depuis un système de fichiers FSX pour ONTAP vers un cluster ONTAP sur site depuis la console d'usine des workloads.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/reverse-replication.html["Réplication inverse"]



==== Réplication de volume de protection des données

Il est désormais possible de répliquer des volumes de protection des données.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/cascade-replication.html["Réplication d'un volume de protection des données"]



==== Sélection de plusieurs volumes

La sélection de plusieurs volumes est disponible pour vous permettre de sélectionner exactement les volumes à répliquer.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Créer une relation de réplication"]



==== Étiquettes de politique de conservation à long terme

Lorsque vous activez la conservation à long terme pour une relation de réplication, les étiquettes des volumes source et cible doivent correspondre exactement. Désormais, l'usine de workloads BlueXP  peut automatiquement créer des étiquettes de volume source manquantes pour vous.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Créer une relation de réplication"]



=== Nom de fichier FSX pour ONTAP visible lors de la création du volume

Nous avons amélioré la visibilité des systèmes de fichiers FSX pour ONTAP lors de la création des volumes. Lorsque vous créez un volume, le système de fichiers FSX pour ONTAP s'affiche. Vous savez ainsi exactement où le volume est créé.



=== Compte AWS visible dans l'ensemble de la charge de travail stockage

Nous avons amélioré la visibilité des comptes sur la charge de travail de stockage. Le compte AWS s'affiche lorsque vous accédez aux onglets *volumes*, *Storage VM* et *Replication*.



=== Améliorations de l'association de liens

* Vous pouvez rapidement associer un lien à partir d'un système de fichiers FSX pour ONTAP dans l'onglet Inventaire.
* La fabrique de charges de travail BlueXP  prend désormais en charge l'utilisation d'autres informations d'identification utilisateur ONTAP pour l'association de liaisons.




=== Prise en charge de l'authentification de liens pour AWS secrets Manager

Vous avez désormais la possibilité d'utiliser les secrets d'AWS secrets Manager pour authentifier les liens afin de ne pas avoir à utiliser les informations d'identification stockées dans l'usine de workloads BlueXP .



=== Assistance de suivi

Tracker fournit désormais des réponses API pour que vous puissiez voir la sortie de l'API REST associée à la tâche.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/monitor-operations.html["Surveiller les opérations avec Tracker"]



=== Validation de la capacité lors de la restauration d'un volume à partir d'une sauvegarde

Lors de la restauration d'un volume à partir d'une sauvegarde, l'usine de workloads BlueXP  détermine si vous disposez de suffisamment de capacité pour la restauration et peut ajouter automatiquement de la capacité de Tier de stockage SSD si ce n'est pas le cas.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/restore-from-backup.html["Restaurer un volume à partir d'une sauvegarde"]



=== Prise en charge d'autres informations d'identification utilisateur ONTAP

L'usine de workloads prend désormais en charge d'autres ensembles d'identifiants ONTAP pour la création de systèmes de fichiers afin de minimiser les risques liés à la sécurité. Au lieu d'utiliser uniquement l'utilisateur fsxadmin, vous pouvez sélectionner un autre ensemble d'informations d'identification ONTAP ou choisir de ne pas fournir de mot de passe aux utilisateurs fsxadmin et vsaadmin.



=== Mise à jour de la terminologie des autorisations

L'interface utilisateur et la documentation de l'usine de charge de travail utilisent désormais « lecture seule » pour faire référence aux autorisations de lecture et « lecture/écriture » pour faire référence aux autorisations d'automatisation.
