= Optimisez vos économies grâce au calculateur de stockage pour Amazon Elastic Block Store (EBS)
:allow-uri-read: 




=== Optimisez vos économies grâce au calculateur de stockage pour Amazon Elastic Block Store (EBS)

Workload Factory peut analyser votre utilisation des performances EBS, puis suggérer la configuration FSx for ONTAP la meilleure et la plus rentable afin que vous puissiez économiser davantage en passant à FSx for ONTAP.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/explore-savings.html#explore-savings-for-detected-storage-environments["Découvrez les économies réalisées sur les environnements de stockage détectés dans la console Workload Factory"]



=== Accès rapide à l'écran des ressources à partir de l'inventaire du système de fichiers

Vous pouvez accéder rapidement à un écran de ressources du système de fichiers FSx for ONTAP en sélectionnant le nom du système de fichiers, désormais un lien hypertexte, dans l'inventaire FSx for ONTAP .



=== Découvrir les relations de cache dans la console Workload Factory

Si vous avez des relations _cache_ entre le système de fichiers FSx for ONTAP et un autre type de stockage ONTAP (système sur site, Cloud Volumes ONTAP et FSx for ONTAP), vous pouvez les découvrir et les afficher à partir de la console Workload Factory. Cela vous permet de mieux comprendre les flux de données, d’optimiser l’utilisation du cache et d’améliorer l’efficacité dans les environnements distribués.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/discover-cache-volumes.html["Découvrir et afficher les relations de cache dans la console Workload Factory"]



=== Mise à jour de l'analyse bien architecturée

Workload Factory analyse désormais vos systèmes de fichiers FSx for ONTAP pour la configuration suivante :

Seuil d'utilisation de la capacité du fichier de volume : vérifie si les seuils de capacité du fichier sont définis sur 80 % ou moins. Cela vous aide à éviter de manquer d’espace sur vos systèmes de fichiers.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Affichez l'état bien architecturé de vos systèmes de fichiers FSx for ONTAP"]



==== Améliorations des actions pour les problèmes de configuration

À partir de l'onglet *Analyse bien architecturée* du tableau de bord d'un système de fichiers FSx for ONTAP , au lieu de rejeter une configuration entière pour un système de fichiers, vous pouvez également sélectionner un ou plusieurs volumes dans un système de fichiers à corriger, rejeter ou réactiver.



=== Notification supplémentaire pour le stockage

Le service de notification NetApp Workload Factory inclut la notification hebdomadaire des problèmes de configuration bien architecturés.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html#notification-types-and-messages["Types de notifications et messages dans la documentation de configuration et d'administration de Workload Factory"]



=== Les fichiers immuables prennent en charge la suppression privilégiée

Avec cette fonctionnalité, vous pouvez configurer un accès de suppression privilégié pour les fichiers immuables dans vos systèmes de fichiers FSx for ONTAP . Cela vous permet de protéger les données critiques contre toute suppression accidentelle ou malveillante tout en permettant aux utilisateurs autorisés de contourner le verrouillage et de supprimer ces fichiers si nécessaire. L'activation de la suppression privilégiée est disponible lors de la création d'un volume ou pour les volumes existants.
