= Améliorations apportées à l'onglet Relations de réplication
:allow-uri-read: 




=== Améliorations apportées à l'onglet Relations de réplication

Nous avons ajouté plusieurs nouvelles colonnes au tableau des relations de réplication pour vous donner plus d'informations sur vos relations de réplication dans l'onglet *Relations de réplication*. Le tableau comprend désormais les colonnes suivantes :

* Politique SnapMirror
* Système de fichiers source
* Système de fichiers cible
* État de la relation
* Heure du dernier transfert




=== Améliorations de la protection autonome contre les ransomwares de NetApp avec IA (ARP/AI)

Cette version introduit le terme mis à jour « NetApp Autonomous Ransomware Protection with AI (ARP/AI) » pour mieux refléter l'intégration de l'intelligence artificielle dans nos capacités de protection contre les ransomwares.

De plus, les améliorations suivantes ont été apportées à ARP/AI :

* ARP/AI au niveau du volume : vous pouvez désormais activer ARP/AI au niveau du volume, ce qui vous permet de protéger des volumes spécifiques au sein de vos systèmes de fichiers FSx for ONTAP .
* Création automatique de snapshots : vous pouvez définir la stratégie ARP/AI pour prendre des snapshots automatiques et définir la fréquence à laquelle les snapshots sont pris pour les volumes avec ARP/AI activé, améliorant ainsi votre stratégie de protection des données.
* Instantanés immuables : ARP/AI prend désormais en charge les instantanés immuables, qui ne peuvent pas être supprimés ou modifiés, offrant ainsi une couche de sécurité supplémentaire contre les attaques de ransomware.
* Détection : comprend diverses méthodes de détection telles que le taux de données d'entropie élevé au niveau du volume, le taux de création de fichiers, le taux de renommage de fichiers, le taux de suppression de fichiers et l'analyse comportementale, ainsi qu'une extension de fichier jamais vue auparavant qui aide à détecter les anomalies et les attaques potentielles de ransomware.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["Protégez vos données avec NetApp Autonomous Ransomware Protection with AI (ARP/AI)"]



=== Mises à jour d'analyse bien conçues

Workload Factory analyse désormais vos systèmes de fichiers FSx for ONTAP pour les configurations suivantes :

* Fiabilité des données de rétention à long terme : vérifie si les étiquettes attribuées à la stratégie de snapshot du volume source sont identiques aux étiquettes attribuées à la stratégie de rétention à long terme. Lorsque les étiquettes sont identiques, la réplication des données est fiable entre les volumes source et cible.
* Protection autonome contre les ransomwares NetApp avec IA (ARP/AI) : vérifie si ARP/AI est activé sur vos systèmes de fichiers. Cette fonctionnalité vous aide à détecter et à récupérer des attaques de ransomware.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Affichez l'état bien architecturé de vos systèmes de fichiers FSx for ONTAP"]



=== Supprimer une configuration de l'analyse bien architecturée

Vous pouvez désormais ignorer une ou plusieurs configurations de l’analyse bien architecturée. Cela vous permet d'ignorer les configurations spécifiques que vous ne souhaitez pas aborder pour le moment.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Supprimer une configuration de l'analyse bien architecturée"]



=== Prise en charge de Terraform pour la création de liens

Vous pouvez désormais utiliser Terraform depuis Codebox pour créer un lien d'association avec un système de fichiers FSx pour ONTAP . Cette fonctionnalité est destinée aux utilisateurs qui créent des liens manuellement.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Connectez-vous à un système de fichiers FSX pour ONTAP via un lien Lambda"]



=== Nouvelle prise en charge régionale pour explorer les économies de stockage

Les nouvelles régions suivantes sont désormais prises en charge pour explorer les économies pour Amazon Elastic Block Store (EBS), FSx pour Windows File Server et Elastic File Systems (EFS) :

* Mexique
* Thaïlande




=== Améliorations apportées à la création et à la gestion des partages SMB/CIFS

Vous pouvez désormais créer des partages SMB/CIFS qui pointent vers des répertoires au sein d’un volume. Dans le volume, vous pourrez voir quels partages existent, vers où pointent les partages et les autorisations accordées à des utilisateurs et groupes spécifiques.

Pour les volumes de protection des données, le flux de création d'un partage SMB/CIFS inclut désormais la création d'un chemin de jonction vers le volume à des fins de montage.

link:https://review.docs.netapp.com/us-en/workload-fsx-ontap_grogu-5684-wa-dismiss/manage-cifs-share.html#create-a-cifs-share-for-a-volume["Créer un partage CIFS pour un volume"]
