= Gestion automatique de la capacité pour les systèmes scale-out
:allow-uri-read: 




=== Gestion automatique de la capacité pour les systèmes scale-out

L'usine de charges de travail recherche désormais les inodes disponibles dans les volumes et augmente leur nombre en fonction des seuils configurés de gestion automatique de la capacité. Cette fonctionnalité prend en charge la gestion automatique de la capacité pour les systèmes scale-out. Vous pouvez activer la gestion des inodes dans le cadre de la gestion automatique de la capacité.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html["Activez la gestion automatique de la capacité"]



=== API de rééquilibrage FlexGroup

L'usine de charges de travail BlueXP  lance l'API de rééquilibrage FlexGroup qui vous permet d'exécuter un plan de rééquilibrage des données dans une FlexGroup. Le rééquilibrage redistribue les données uniformément aux volumes membres.

link:https://console.workloads.netapp.com/api-doc["Documentation de l'API BlueXP  Workload Factory"]



=== Le formulaire de réplication de données inclut des cas d'utilisation

Le formulaire de données répliquées comprend désormais des cas d'utilisation qui vous permettent de remplir plus facilement le formulaire. Sélectionnez l'un des cas d'utilisation suivants pour la réplication des données : migration, reprise après incident à chaud, reprise après incident à froid, archivage ou autre. Après avoir sélectionné un cas d'utilisation, Workload Factory recommande des valeurs conformément aux meilleures pratiques. Vous pouvez accepter les valeurs présélectionnées ou les personnaliser dans le formulaire.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Réplication des données"]



=== Modifications de la terminologie des règles de Tiering des données

Lorsque vous sélectionnez une règle de Tiering lors de la création de volumes, de la réplication de données ou des mises à jour de règles de Tiering existantes, vous trouverez de nouveaux termes qui décrivent les règles de Tiering.

* _Équilibré (auto)_
* _Optimisation des coûts (tous)_
* _Optimisation des performances (snapshots uniquement)_

