= Tracker disponible pour les opérations de surveillance et de suivi
:allow-uri-read: 




=== Tracker disponible pour les opérations de surveillance et de suivi

La fonctionnalité de surveillance Tracker est désormais disponible dans GenAI. Vous pouvez utiliser Tracker pour surveiller et suivre la progression et l'état des opérations en attente, en cours et terminées, consulter les détails des tâches et sous-tâches opérationnelles, diagnostiquer les problèmes ou les échecs, modifier les paramètres des opérations ayant échoué et relancer les opérations ayant échoué.

link:https://docs.netapp.com/us-en/workload-genai/general/monitor-operations.html["Surveillez les opérations de charge de travail avec Tracker dans l'usine de charge de travail BlueXP"]



=== Choisir un modèle de reranker pour une base de connaissances

Vous pouvez désormais améliorer la pertinence des résultats de requêtes reclassés en sélectionnant un modèle de reranking spécifique à utiliser avec une base de connaissances. GenAI prend en charge les modèles Cohere Rerank et Amazon Rerank.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["Créer une base de connaissances GenAI"]
