= Stockage sécurisé des résultats de données structurées
:allow-uri-read: 




=== Stockage sécurisé des résultats de données structurées

Si les résultats de la requête du chatbot contiennent des données structurées, GenAI peut stocker les résultats dans un compartiment Amazon S3. Lorsque ces résultats sont stockés dans un bucket S3, vous pouvez les télécharger à l’aide du lien de téléchargement dans la session de chat.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["Créer une base de connaissances GenAI"]



=== Disponibilité du serveur MCP

NetApp fournit désormais un serveur Model Context Protocol (MCP) avec NetApp Workload Factory pour GenAI. Vous pouvez installer le serveur localement pour permettre aux clients MCP externes de découvrir et de récupérer les résultats de requête à partir d'une base de connaissances GenAI.

link:https://github.com/NetApp/mcp/tree/main/NetApp-KnowledgeBase-MCP-server["Serveur NetApp Workload Factory GenAI MCP"^]
