= Prise en charge du connecteur NetApp pour Amazon Q Business
:allow-uri-read: 




=== Prise en charge du connecteur NetApp pour Amazon Q Business

Cette version de GenAI introduit la prise en charge de NetApp Connector pour Amazon Q Business, vous permettant de créer des connecteurs pour Amazon Q Business. Profitez rapidement et facilement de l'assistant IA Amazon Q Business avec moins de configuration initiale qu'en construisant une base de connaissances GenAI pour le socle Amazon.

link:https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html["Créer un connecteur NetApp pour Amazon Q Business"]



=== Prise en charge améliorée des modèles de chat

GenAI prend désormais en charge les modèles de chat supplémentaires suivants pour les bases de connaissances :

* link:https://docs.mistral.ai/getting-started/models/models_overview/["Modèles d'IA Mistral"^]
* link:https://docs.aws.amazon.com/bedrock/latest/userguide/titan-text-models.html["Modèles texte Amazon Titan"^]
* link:https://www.llama.com/docs/model-cards-and-prompt-formats/["Modèles META Llama"^]
* link:https://docs.ai21.com/["Modèles Jamba 1.5"^]
* link:https://docs.cohere.com/docs/the-cohere-platform["Modèles Cohere Command"^]
* link:https://aws.amazon.com/bedrock/deepseek/["Modèles DeepSeek"^]


GenAI prend en charge les modèles de chaque fournisseur pris en charge par Amazon Bedrock : link:https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html["Modèles de base pris en charge dans Amazon Bedrock"^]

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["Créer une base de connaissances GenAI"]



=== Mise à jour de la terminologie des autorisations

L'interface utilisateur et la documentation de l'usine de la charge de travail utilisent désormais « lecture seule » pour faire référence aux autorisations de lecture et « lecture-écriture » pour faire référence aux autorisations d'automatisation.
