= Optimisation améliorée
:allow-uri-read: 




=== Optimisation améliorée

Lors de l'optimisation de vos environnements de base de données, de nouvelles évaluations d'optimisation, des corrections et l'affichage de plusieurs ressources sont disponibles.



==== Évaluations de résilience

Ces améliorations incluent de nouvelles évaluations de la résilience pour vérifier que les fonctionnalités de redondance des données et de reprise d'activité sont configurées pour vos environnements de base de données.

* Sauvegardes FSX pour ONTAP : analyse si les systèmes de fichiers FSX pour ONTAP qui desservent les volumes de l'instance SQL Server sont configurés avec des sauvegardes FSX pour ONTAP planifiées.
* Réplication interrégionale : vérifie si les systèmes de fichiers FSX pour ONTAP qui servent des instances de Microsoft SQL Server sont configurés avec la réplication interrégionale.




==== Résolution des problèmes de calcul

La correction RSS (Receive Side Scaling) configure RSS pour distribuer le traitement réseau sur plusieurs processeurs et assurer une distribution de charge efficace.



==== Correction locale des snapshots

La correction locale des snapshots définit des règles de snapshot pour les volumes de vos instances Microsoft SQL Server afin de préserver la résilience de vos environnements de base de données en cas de perte de données.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Optimiser les configurations"]



==== Prise en charge de la sélection de plusieurs ressources

Lors de l'optimisation des configurations de base de données, vous pouvez désormais sélectionner des ressources spécifiques au lieu de toutes les ressources.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Optimiser les configurations"]



=== Vue Inventaire améliorée

L'onglet Inventaire de la console d'usine des workloads a été rationalisé de sorte qu'il ne contienne que les serveurs SQL s'exécutant sur Amazon FSX pour NetApp ONTAP. Vous trouverez maintenant des serveurs SQL sur site et s'exécutant sur Amazon Elastic Block Store et Amazon FSX pour Windows File Server dans l'onglet économies Explore.



=== Création rapide disponible pour le déploiement du serveur PostgreSQL

Vous pouvez utiliser cette option de déploiement rapide pour créer un serveur PostgreSQL avec une configuration haute disponibilité et les meilleures pratiques intégrées.

link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["Créez un serveur PostgreSQL en usine de charges de travail BlueXP"]
