= Nom de snapshot personnalisé
:allow-uri-read: 




=== Nom de snapshot personnalisé

Vous pouvez maintenant fournir un nom d'instantané pour un instantané ad hoc.

link:https://docs.netapp.com/us-en/workload-genai/manage-knowledgebase.html#protect-a-knowledge-base-with-snapshots["Protégez une base de connaissances avec des instantanés"]



=== Nom d'instance de moteur d'IA personnalisé

Vous pouvez maintenant attribuer un nom personnalisé à l'instance du moteur d'IA pendant le déploiement.

link:https://docs.netapp.com/us-en/workload-genai/deploy-infrastructure.html["Déployez l'infrastructure GenAI"]



=== Reconstruction de l'infrastructure GenAI corrompue ou manquante

Si votre instance de moteur d'IA est corrompue ou supprimée, vous pouvez laisser la charge de travail se reconstruire en usine. Workload Factory rattache automatiquement vos bases de connaissances à l'infrastructure une fois la reconstruction terminée, afin qu'elles soient prêtes à l'emploi.

link:https://docs.netapp.com/us-en/workload-genai/troubleshooting.html["Dépannage"]
