= Prise en charge du service de notification de l'usine de charge de travail BlueXP
:allow-uri-read: 




=== Prise en charge du service de notification de l'usine de charge de travail BlueXP

Le service de notification de l'usine de charge de travail BlueXP permet à l'usine de charge de travail d'envoyer des notifications au service d'alertes BlueXP ou à une rubrique Amazon SNS. Les notifications envoyées aux alertes BlueXP apparaissent dans le panneau des alertes BlueXP. Lorsque la fabrique de charges de travail publie des notifications dans une rubrique Amazon SNS, les abonnés à cette rubrique (tels que les personnes ou d'autres applications) reçoivent les notifications aux points de terminaison configurés pour cette rubrique (tels que les e-mails ou les SMS).

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Configurer les notifications de l'usine de charge de travail BlueXP"^]



=== Améliorations du tableau de bord de stockage

Le tableau de bord Stockage de la console Workload Factory inclut de nouvelles cartes pour les opportunités d'économies. La carte en haut du tableau de bord affiche le nombre d'opportunités d'économies pour les environnements de stockage exécutés sur Amazon Elastic Block Store (EBS), Amazon FSx for Windows File Server et Amazon Elastic File Systems (EFS). En bas du tableau de bord, trois nouvelles cartes affichent les opportunités d'économies par service de stockage Amazon : EBS, FSx for Windows File Server et EFS. À partir de chaque carte, vous pouvez explorer les opportunités d'économies plus en détail.

À partir de la carte de couverture de protection et de la carte d'intégrité des relations de réplication de FSx for ONTAP, vous pouvez vérifier la présence de volumes partiellement protégés dans vos systèmes de fichiers FSx for ONTAP et identifier les problèmes liés aux relations de réplication. Dans les deux cas, vous pouvez prendre des mesures pour résoudre les problèmes.



=== Améliorations de l'onglet Volume

L'onglet Volumes de la console Workload Factory a été amélioré pour offrir une vue plus complète de vos systèmes de fichiers FSx for ONTAP. Ces améliorations incluent de nouvelles cartes pour la capacité SSD, le pool de capacité et la protection autonome contre les ransomwares NetApp avec IA (ARP/AI). Ces cartes résument l'utilisation de la capacité et la protection ARP/AI pour tous les volumes du système de fichiers.



=== Prise en charge des systèmes de fichiers Amazon FSX pour NetApp ONTAP de deuxième génération

Workload Factory prend désormais en charge les systèmes de fichiers Amazon FSx for NetApp ONTAP de deuxième génération. Vous pouvez créer, gérer et surveiller des systèmes de fichiers de deuxième génération dans la console Workload Factory. Toutes les nouvelles régions commerciales sont prises en charge.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Créer un système de fichiers de deuxième génération dans Workload Factory"]



=== Prise en charge du volume FlexVol pour rééquilibrer la capacité du volume

Les volumes FlexVol sont détectables dans la console Workload Factory. Vous pouvez vérifier l'équilibre de vos volumes FlexVol et les rééquilibrer pour redistribuer la capacité lorsque des déséquilibres apparaissent au fil du temps, dus à l'ajout de nouveaux fichiers et à leur croissance.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/rebalance-volume.html["Rééquilibrer la capacité d'un volume FlexVol"]



=== Mise à jour de la terminologie

Le terme « Autonomous Ransomware Protection » (ARP) a été mis à jour en « NetApp Autonomous Ransomware Protection with AI » (ARP/AI) dans la console de l'usine de charge de travail.



=== ARP/AI activé par défaut pour les nouveaux volumes

Lorsque vous créez un volume dans la console Workload Factory, la protection autonome contre les ransomwares NetApp avec IA (ARP/AI) est activée par défaut si le système de fichiers dispose d'une stratégie ARP/AI. Cela signifie que le volume est automatiquement protégé contre les attaques de ransomware grâce à des fonctionnalités de détection et de réponse basées sur l'IA.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Créer un volume dans la fabrique de charges de travail"]



=== Prise en charge de la réplication pour les fichiers immuables

Workload Factory prend en charge la réplication de volumes immuables d'un système FSx for ONTAP vers un autre système de fichiers FSx for ONTAP afin de protéger les données critiques contre toute suppression accidentelle ou attaque malveillante comme les rançongiciels. Le volume cible et son système de fichiers hôte sont immuables, ou verrouillés, et les données du système de fichiers cible ne peuvent être ni modifiées ni supprimées avant la fin de la période de conservation.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Apprenez à créer une relation de réplication"]



=== Améliorations de la création de liens

Les améliorations suivantes ont été apportées au processus de création de liens dans la console de l’usine de charge de travail.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Connectez-vous à un système de fichiers FSX pour ONTAP via un lien Lambda"]



==== Gérer le rôle d'exécution et les autorisations IAM lors de la création du lien

Vous pouvez désormais gérer le rôle d'exécution IAM et la politique d'autorisations associée en créant un lien dans la console Workload Factory. Un lien établit la connectivité entre votre compte Workload Factory et un ou plusieurs systèmes de fichiers FSx for ONTAP. Vous disposez de deux options pour attribuer le rôle d'exécution IAM et les autorisations associées : automatiquement ou par l'utilisateur. La gestion du rôle d'exécution et de la politique d'autorisations associée dans Workload Factory vous évite d'avoir recours à du code tiers.



==== Prise en charge de Terraform pour la création de liens

Vous pouvez désormais utiliser Terraform depuis Codebox pour créer un lien à associer à un système de fichiers FSx for ONTAP. Cette fonctionnalité est réservée aux utilisateurs qui créent des liens manuellement.
