= Améliorations du tableau de bord bases de données
:allow-uri-read: 




=== Améliorations du tableau de bord bases de données

Une nouvelle conception du tableau de bord inclut les graphiques et améliorations suivants :

* Le graphique de distribution des hôtes indique le nombre d'hôtes Microsoft SQL Server et d'hôtes PostgreSQL
* Les détails de la distribution des instances comprennent le nombre total d'instances détectées et le nombre d'instances gérées de Microsoft SQL Server et PostgreSQL
* Les détails de distribution des bases de données incluent le nombre total de bases de données et le nombre de bases de données Microsoft SQL Server et PostgreSQL gérées
* Score et États d'optimisation pour les instances gérées et en ligne
* Détails d'optimisation pour les catégories de stockage, de calcul et d'applications
* Détails d'optimisation pour les configurations d'instances Microsoft SQL Server, telles que le dimensionnement du stockage, l'infrastructure de stockage, le stockage ONTAP, le calcul et les applications
* Économies potentielles pour les workloads de base de données s'exécutant sur les environnements de stockage Amazon Elastic Block Store et FSX pour serveur de fichiers Windows par rapport au stockage Amazon FSX pour NetApp ONTAP




=== Nouveau statut « terminé avec problèmes » dans surveillance des travaux

La fonction de surveillance des travaux pour les bases de données fournit désormais le nouvel état « terminé avec problèmes » pour vous permettre d'apprendre quels sous-travaux ont rencontré des problèmes et quels sont les problèmes.

link:https://docs.netapp.com/us-en/workload-databases/monitor-databases.html["Surveillez vos bases de données"]



=== Évaluation et optimisation des licences Microsoft SQL Server surprovisionnées

Le calculateur d'économies évalue maintenant si Enterprise Edition est nécessaire pour votre déploiement Microsoft SQL Server. Si une licence est surprovisionnée, le calculateur recommande la mise à niveau vers une version antérieure. Vous pourrez rétrograder automatiquement la licence dans les bases de données en optimisant l'application.

* link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html["Découvrez les économies réalisées avec FSX for ONTAP pour les workloads de bases de données"^]
* link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Optimisez vos workloads SQL Server"]

