= Nouveau tableau de bord bien conçu disponible pour tous les systèmes FSx for ONTAP
:allow-uri-read: 




[[new-well-architected-dashboard-available-for-all-fsx-for-ontap-systems]]
=== Nouveau tableau de bord bien conçu disponible pour tous les systèmes FSx for ONTAP

L'analyse bien architecturée est désormais disponible pour les systèmes de fichiers FSx for ONTAP depuis le nouveau tableau de bord bien architecturé dans NetApp Workload Factory. Le nouveau tableau de bord offre une vue centralisée de tous vos systèmes de fichiers, tous comptes et régions confondus, ainsi que de leurs configurations en un seul endroit. Une notification contextuelle apparaît lorsque vous consultez l’onglet *Well-architected* depuis un système de fichiers. Accédez au nouveau tableau de bord en sélectionnant *Well-architected* dans le menu de navigation de gauche de Workload Factory.

Vous pouvez toujours accéder à l'analyse bien architecturée pour un système de fichiers spécifique et à partir de l'option de menu *Well-architected* dans Storage.



[[volumes-explorer]]
=== Explorateur de volumes

Volumes Explorer vous offre une vue simple et consultable de tous vos volumes dans NetApp Workload Factory. Identifiez rapidement les volumes dédiés aux charges de travail par blocs ou par fichiers. Consultez la taille logique, la capacité physique utilisée et l’utilisation des fonctionnalités d’efficacité du stockage (compression, déduplication et compactage) de chaque volume. Filtrez et triez les volumes par nom, état (disponible/défaillant), latence, taille, capacité utilisée et fonctionnalités de protection.



[[enhanced-email-notifications-for-replication-delays]]
=== Notifications par e-mail améliorées en cas de retards de réplication

Les notifications par e-mail concernant les retards de réplication contiennent désormais plus de détails sur la relation concernée. Cette notification vous permet d'identifier rapidement la relation concernée et de l'examiner dans la console Workload Factory.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/track-replication-delays.html["Activer les notifications en cas de retard de réplication"]



[[block-device-creation-enhancement]]
=== Amélioration de la création de périphériques de bloc

Workload Factory prend en charge la création de périphériques de blocs à partir d'un instantané de volume.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-block-device.html["Créez un périphérique de stockage par blocs à partir d'un instantané de volume dans Workload Factory"]
