= Explorateur de volumes
:allow-uri-read: 




[[volumes-explorer]]
=== Explorateur de volumes

Volumes Explorer vous offre une vue simple et consultable de tous vos volumes dans NetApp Workload Factory. Identifiez rapidement les volumes dédiés aux charges de travail par blocs ou par fichiers. Consultez la taille logique, la capacité physique utilisée et l’utilisation des fonctionnalités d’efficacité du stockage (compression, déduplication et compactage) de chaque volume. Filtrez et triez les volumes par nom, état (disponible/défaillant), latence, taille, capacité utilisée et fonctionnalités de protection.



[[enhanced-email-notifications-for-replication-delays]]
=== Notifications par e-mail améliorées en cas de retards de réplication

Les notifications par e-mail concernant les retards de réplication contiennent désormais plus de détails sur la relation concernée. Cette notification vous permet d'identifier rapidement la relation concernée et de l'examiner dans la console Workload Factory.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/track-replication-delays.html["Activer les notifications en cas de retard de réplication"]



[[block-device-creation-enhancement]]
=== Amélioration de la création de périphériques de bloc

Workload Factory prend en charge la création de périphériques de blocs à partir d'un instantané de volume.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-block-device.html["Créez un périphérique de stockage par blocs à partir d'un instantané de volume dans Workload Factory"]
