= Mises à jour d'analyse bien conçues
:allow-uri-read: 




=== Mises à jour d'analyse bien conçues

Workload Factory analyse vos systèmes de fichiers Amazon FSx for ONTAP pour les *volumes NAS inactifs*. L'analyse de configuration identifie les volumes NAS qui ne sont pas activement utilisés et recommande des actions pour optimiser l'utilisation du stockage et réduire les coûts.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Mettre en œuvre des systèmes de fichiers FSx for ONTAP bien architecturés"]



=== Fonctionnalité de table de journal pour les points d'accès S3

La fonctionnalité Journal table permet de gérer le stockage d'objets S3 de FSx ONTAP à grande échelle, facilitant ainsi l'audit des événements d'accès utilisateur et des opérations sur les objets dans vos compartiments. Avec Workload Factory, vous pouvez configurer des analyses automatiques de vos compartiments et tables S3 afin de conserver un historique des événements, affichant tous les objets, leurs détails et les actions des utilisateurs.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/setup-journal-table.html["Configurez l'infrastructure de la table de journalisation pour NetApp Workload Factory"]



=== Prise en charge de la gestion des igroups existants

Workload Factory prend en charge la gestion des igroups existants. Vous pouvez ajouter ou supprimer des périphériques de blocs et des initiateurs hôtes afin de garantir la livraison de votre charge de travail déployée dans les délais impartis.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-storage.html["Gérez le stockage bloc dans NetApp Workload Factory"]



=== Prise en charge de la spécification de l'agrégat pour les volumes FlexVol

Workload Factory permet de créer des volumes FlexVol sur un agrégat choisi. Cela vous permet de répartir la charge de capacité et de performance sur l'ensemble des ressources du système de fichiers.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Créez un FlexVol volume dans NetApp Workload Factory"]



=== Dernier temps d'accès pour les périphériques de blocs

Workload Factory indique le dernier temps d'accès aux périphériques de stockage par blocs. L'heure est basée sur votre dernier accès à l'igroup dans Workload Factory. Savoir quand chaque périphérique de stockage par blocs a été utilisé pour la dernière fois vous permet d'optimiser vos ressources.
